USE [DataService]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO




CREATE TABLE [dbo].[TB_REFERENCE_TYPE](
	[TYPE_ID] [int] NOT NULL,
	[TYPE_NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](200) NOT NULL CONSTRAINT [DF_tb_REFERENCE_TYPE_DESCRIPTION]  DEFAULT (''),
	[NOTES] [nvarchar](200) NOT NULL CONSTRAINT [DF_tb_REFERENCE_TYPE_NOTES]  DEFAULT (''),
 CONSTRAINT [PK_tb_REFERENCE_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (1, N'Report', N'Old Code was E', N'Consider using Dissertation or Research Project when appropriate')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (2, N'Book, Whole', N'', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (3, N'Book, Chapter', N'', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (4, N'Dissertation', N'Old Code Was G', N'Use the Edition field to specify the thesis type')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (5, N'Conference Proceedings', N'Old Code Was K', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (6, N'Document From Internet Site', N'This is a single document', N'Date fields refer to publication date, if known')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (7, N'Web Site', N'This is a multi-page website ', N'URL field should contain the root of the site hierarchy, date fields should refer to last visited date')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (8, N'DVD, Video, Media', N'', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (9, N'Research project', N'', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (10, N'Article In A Periodical', N'Newspapers, magazines and similar. Old codes are "PER" and F(newspaper)', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (11, N'Interview', N'Old code was INT', N'Author role = 0 is for the Interviewer, Author role = 1 for the Interviewee')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (12, N'Generic', N'Whatever does not fit any of the above, only old code that fits here is H(trade catalogue)', N'')
INSERT [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID], [TYPE_NAME], [DESCRIPTION], [NOTES]) VALUES (14, N'Journal, Article', N'Used also for old "Journal, Whole", D(Journal short form) and "JOUR" codes', N'')

GO

CREATE TABLE [dbo].[TB_REFERENCE](
	[REFERENCE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TYPE_ID] [int] NOT NULL CONSTRAINT [DF_tb_REFERENCE_TYPE_ID]  DEFAULT ((0)),
	[TITLE] [nvarchar](4000) NULL CONSTRAINT [DF_tb_REFERENCE_TITLE]  DEFAULT (''),
	[PARENT_TITLE] [nvarchar](4000) NULL CONSTRAINT [DF_tb_REFERENCE_PARENT_TITLE]  DEFAULT (''),
	[SHORT_TITLE] [nvarchar](70) NULL CONSTRAINT [DF_tb_REFERENCE_SHORT_TITLE]  DEFAULT (''),
	[DATE_CREATED] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NULL CONSTRAINT [DF_tb_REFERENCE_CREATED_BY]  DEFAULT (''),
	[DATE_EDITED] [datetime] NULL,
	[EDITED_BY] [nvarchar](50) NULL,
	[YEAR] [nchar](4) NULL CONSTRAINT [DF_tb_REFERENCE_YEAR]  DEFAULT ((0)),
	[MONTH] [varchar](10) NULL CONSTRAINT [DF_tb_REFERENCE_MONTH]  DEFAULT ((0)),
	[STANDARD_NUMBER] [nvarchar](255) NULL CONSTRAINT [DF_tb_REFERENCE_STANDARD_NUMBER]  DEFAULT (''),
	[CITY] [nvarchar](100) NULL CONSTRAINT [DF_tb_REFERENCE_CITY]  DEFAULT (''),
	[COUNTRY] [nvarchar](100) NULL CONSTRAINT [DF_tb_REFERENCE_COUNTRY]  DEFAULT (''),
	[PUBLISHER] [nvarchar](1000) NULL CONSTRAINT [DF_tb_REFERENCE_PUBLISHER]  DEFAULT (''),
	[INSTITUTION] [nvarchar](1000) NULL CONSTRAINT [DF_tb_REFERENCE_INSTITUTION]  DEFAULT (''),
	[VOLUME] [nvarchar](56) NULL CONSTRAINT [DF_tb_REFERENCE_VOLUME]  DEFAULT (''),
	[PAGES] [nvarchar](50) NULL CONSTRAINT [DF_tb_REFERENCE_PAGES]  DEFAULT (''),
	[EDITION] [nvarchar](200) NULL CONSTRAINT [DF_tb_REFERENCE_EDITION]  DEFAULT (''),
	[ISSUE] [nvarchar](100) NULL CONSTRAINT [DF_tb_REFERENCE_ISSUE]  DEFAULT (''),
	[IS_LOCAL] [bit] NULL CONSTRAINT [DF_tb_REFERENCE_IS_LOCAL]  DEFAULT ((0)),
	[AVAILABILITY] [nvarchar](255) NULL CONSTRAINT [DF_tb_REFERENCE_AVAILABILITY]  DEFAULT (''),
	[URL] [nvarchar](2000) NULL CONSTRAINT [DF_tb_REFERENCE_URL]  DEFAULT (''),
	[ABSTRACT] [nvarchar](max) NULL CONSTRAINT [DF_tb_REFERENCE_ABSTRACT]  DEFAULT (''),
	[COMMENTS] [nvarchar](max) NULL CONSTRAINT [DF_tb_REFERENCE_COMMENTS]  DEFAULT (''),
	[MESHTERMS] [nvarchar](max) NULL CONSTRAINT [DF_tb_REFERENCE_MESHTERMS]  DEFAULT (''),
	[KEYWORDS] [nvarchar](max) NULL CONSTRAINT [DF_tb_REFERENCE_KEYWORDS]  DEFAULT (''),
 CONSTRAINT [PK_tb_REFERENCE] PRIMARY KEY CLUSTERED 
(
	[REFERENCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_REFERENCE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REFERENCE_TB_REFERENCE_TYPE] FOREIGN KEY([TYPE_ID])
REFERENCES [dbo].[TB_REFERENCE_TYPE] ([TYPE_ID])
GO

ALTER TABLE [dbo].[TB_REFERENCE] CHECK CONSTRAINT [FK_TB_REFERENCE_TB_REFERENCE_TYPE]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_REFERENCE_AUTHOR](
	[REFERENCE_AUTHOR_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[REFERENCE_ID] [bigint] NOT NULL,
	[LAST] [nvarchar](50) NOT NULL,
	[FIRST] [nvarchar](50) NOT NULL CONSTRAINT [DF_tb_REFERENCE_AUTHORS_First]  DEFAULT (''),
	[ROLE] [tinyint] NOT NULL CONSTRAINT [DF_tb_REFERENCE_AUTHOR_ROLE]  DEFAULT ((0)),
	[RANK] [smallint] NOT NULL,
 CONSTRAINT [PK_tb_REFERENCE_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[REFERENCE_AUTHOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_tb_REFERENCE_AUTHORS] UNIQUE NONCLUSTERED 
(
	[REFERENCE_ID] ASC,
	[LAST] ASC,
	[FIRST] ASC,
	[ROLE] ASC,
	[RANK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TB_REFERENCE_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_tb_REFERENCE_AUTHORS_tb_REFERENCE] FOREIGN KEY([REFERENCE_ID])
REFERENCES [dbo].[TB_REFERENCE] ([REFERENCE_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_REFERENCE_AUTHOR] CHECK CONSTRAINT [FK_tb_REFERENCE_AUTHORS_tb_REFERENCE]
GO

CREATE FUNCTION  [dbo].[fn_REBUILD_AUTHORS]

(

@id bigint,
@role tinyint = 0

)

RETURNS nvarchar(max)

   

    BEGIN

        declare @res nvarchar(max)

        declare @res2 nvarchar(max)

        DECLARE cr CURSOR FAST_FORWARD FOR SELECT [LAST] + ' ' + [FIRST] 

        FROM [tb_REFERENCE_AUTHOR]  where REFERENCE_ID = @id AND ROLE = @role

        ORDER BY [RANK]

        open cr

        set @res = ''

        FETCH NEXT FROM cr INTO @res2

         WHILE @@FETCH_STATUS = 0

        BEGIN

                Set @res = @res  + @res2

                FETCH NEXT FROM cr INTO @res2

                set @res = @res + '; '

                END
		CLOSE cr
	    DEALLOCATE cr

        return @res

    END;

-- END OF: De-normalising function ByS --
GO