--Use Reviewer
--GO

--/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
--IF COL_LENGTH('TB_REVIEW', 'MAG_ENABLED') IS NULL
--begin
--BEGIN TRANSACTION
--SET QUOTED_IDENTIFIER ON
--SET ARITHABORT ON
--SET NUMERIC_ROUNDABORT OFF
--SET CONCAT_NULL_YIELDS_NULL ON
--SET ANSI_NULLS ON
--SET ANSI_PADDING ON
--SET ANSI_WARNINGS ON
----select 1
--COMMIT
--BEGIN TRANSACTION
--ALTER TABLE dbo.TB_REVIEW ADD
--	MAG_ENABLED int NULL

--ALTER TABLE dbo.TB_REVIEW SET (LOCK_ESCALATION = TABLE)
----select 2
--COMMIT
--end
--GO
--update dbo.TB_REVIEW Set MAG_ENABLED = 0 where MAG_ENABLED is null

--USE [Reviewer]
--GO

--/****** Object:  StoredProcedure [dbo].[st_ReviewInsert]    Script Date: 02/10/2019 23:04:02 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE OR ALTER procedure [dbo].[st_ReviewInsert]
--(
--	@REVIEW_NAME NVARCHAR(255),
--	@CONTACT_ID INT,
--	@NEW_REVIEW_ID INT OUTPUT
--)

--As

--SET NOCOUNT ON

--	INSERT INTO TB_REVIEW(REVIEW_NAME, FUNDER_ID, DATE_CREATED, MAG_ENABLED)
--	VALUES (@REVIEW_NAME, @CONTACT_ID, CURRENT_TIMESTAMP, 0)

--	SET @NEW_REVIEW_ID = @@IDENTITY
	
--	DECLARE @NEW_CONTACT_REVIEW_ID INT
	
--	INSERT INTO TB_REVIEW_CONTACT(CONTACT_ID, REVIEW_ID)
--	VALUES (@CONTACT_ID, @NEW_REVIEW_ID)
	
--	SET @NEW_CONTACT_REVIEW_ID = @@IDENTITY
	
--	INSERT INTO TB_CONTACT_REVIEW_ROLE(REVIEW_CONTACT_ID, ROLE_NAME)
--	VALUES(@NEW_CONTACT_REVIEW_ID, 'AdminUser')
	
	
	
	

--SET NOCOUNT OFF

--GO
--USE [Reviewer]
--GO

--/****** Object:  StoredProcedure [dbo].[st_ReviewInfoUpdate]    Script Date: 02/10/2019 23:06:23 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE OR ALTER procedure [dbo].[st_ReviewInfoUpdate]
--(
--	@REVIEW_ID int
--,	@SCREENING_CODE_SET_ID int
--,	@SCREENING_MODE nvarchar(10)
--,	@SCREENING_RECONCILLIATION nvarchar(10)
--,	@SCREENING_WHAT_ATTRIBUTE_ID bigint
--,	@SCREENING_N_PEOPLE int
--,	@SCREENING_AUTO_EXCLUDE bit
--,	@SCREENING_MODEL_RUNNING bit
--,	@SCREENING_INDEXED bit
--,	@MAG_ENABLED INT
--)

--As

--SET NOCOUNT ON

--UPDATE TB_REVIEW
--	SET SCREENING_CODE_SET_ID = @SCREENING_CODE_SET_ID
--,		SCREENING_MODE = @SCREENING_MODE
--,		SCREENING_RECONCILLIATION = @SCREENING_RECONCILLIATION
--,		SCREENING_WHAT_ATTRIBUTE_ID = @SCREENING_WHAT_ATTRIBUTE_ID
--,		SCREENING_N_PEOPLE = @SCREENING_N_PEOPLE
--,		SCREENING_AUTO_EXCLUDE = @SCREENING_AUTO_EXCLUDE
----,		SCREENING_MODEL_RUNNING = @SCREENING_MODEL_RUNNING
--,		SCREENING_INDEXED = @SCREENING_INDEXED
--,		MAG_ENABLED = @MAG_ENABLED
--WHERE REVIEW_ID = @REVIEW_ID
	

--SET NOCOUNT OFF


--GO




