USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ItemIncludeExclude]    Script Date: 03/02/2020 14:52:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_ItemIncludeExclude]
(
	@INCLUDE BIT,
	@ITEM_ID_LIST varchar(max),
	@REVIEW_ID INT,
	@ATTRIBUTE_ID BIGINT,
	@SET_ID INT
)

As

SET NOCOUNT ON

IF(@ITEM_ID_LIST = '')
BEGIN
	UPDATE TB_ITEM_REVIEW
	set IS_INCLUDED = @INCLUDE, IS_DELETED = 'FALSE'
	WHERE REVIEW_ID = @REVIEW_ID 
		 AND ITEM_ID IN
		(SELECT TB_ITEM_ATTRIBUTE.ITEM_ID FROM TB_ITEM_ATTRIBUTE
			INNER JOIN TB_ITEM_SET ON TB_ITEM_SET.ITEM_ID = TB_ITEM_ATTRIBUTE.ITEM_ID
			AND TB_ITEM_SET.ITEM_SET_ID = TB_ITEM_ATTRIBUTE.ITEM_SET_ID
			AND TB_ITEM_SET.IS_COMPLETED = 'TRUE' AND TB_ITEM_SET.SET_ID = @SET_ID
			AND TB_ITEM_ATTRIBUTE.ATTRIBUTE_ID = @ATTRIBUTE_ID
		)
		AND not( IS_DELETED = 1 and IS_INCLUDED = 1)--this leaves shadow items alone
END
ELSE
BEGIN
	UPDATE TB_ITEM_REVIEW
	set IS_INCLUDED = @INCLUDE, IS_DELETED = 'FALSE'
	WHERE REVIEW_ID = @REVIEW_ID 
		 AND ITEM_ID IN
		(SELECT VALUE FROM dbo.fn_Split_int(@ITEM_ID_LIST, ','))
		AND not( IS_DELETED = 1 and IS_INCLUDED = 1)--this leaves shadow items alone
END

SET NOCOUNT OFF
GO