USE [Reviewer]
GO

IF NOT EXISTS 
	(SELECT * 
	FROM sys.indexes 
	WHERE name='IX_TB_ITEM_ATTRIBUTE_ITEM_ARM_ID' AND object_id = OBJECT_ID('dbo.TB_ITEM_ATTRIBUTE'))
BEGIN
	CREATE NONCLUSTERED INDEX [IX_TB_ITEM_ATTRIBUTE_ITEM_ARM_ID]
	ON [dbo].[TB_ITEM_ATTRIBUTE] ([ITEM_ARM_ID]) INCLUDE ([ITEM_ATTRIBUTE_ID])
END
GO