USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ClassifierModels]    Script Date: 19/06/2020 11:06:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_ClassifierModels]
(
	@REVIEW_ID INT
)

As

SET NOCOUNT ON

	select MODEL_ID, MODEL_TITLE, REVIEW_ID, A1.ATTRIBUTE_NAME ATTRIBUTE_ON, A2.ATTRIBUTE_NAME ATTRIBUTE_NOT_ON,
		CONTACT_NAME, tb_CLASSIFIER_MODEL.CONTACT_ID, ACCURACY, AUC, [PRECISION], RECALL,
		ATTRIBUTE_ID_ON, ATTRIBUTE_ID_NOT_ON
		from tb_CLASSIFIER_MODEL
	INNER JOIN TB_ATTRIBUTE A1 ON A1.ATTRIBUTE_ID = tb_CLASSIFIER_MODEL.ATTRIBUTE_ID_ON
	INNER JOIN TB_ATTRIBUTE A2 ON A2.ATTRIBUTE_ID = tb_CLASSIFIER_MODEL.ATTRIBUTE_ID_NOT_ON
	INNER JOIN TB_CONTACT ON TB_CONTACT.CONTACT_ID = tb_CLASSIFIER_MODEL.CONTACT_ID
	
	where REVIEW_ID = @REVIEW_ID
	order by MODEL_ID

SET NOCOUNT OFF
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ClassifierUpdateModelTitle]    Script Date: 19/06/2020 13:10:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create or ALTER procedure [dbo].[st_ClassifierUpdateModelTitle]
(
	@MODEL_ID INT
,	@TITLE nvarchar(1000) = NULL
)

As

SET NOCOUNT ON


BEGIN

	update tb_CLASSIFIER_MODEL
		set MODEL_TITLE = @TITLE
		
	WHERE MODEL_ID = @MODEL_ID
END

SET NOCOUNT OFF
GO