USE [REVIEWER]
go
/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
IF COL_LENGTH('dbo.TB_REVIEW','ENABLE_ARMS') IS NULL
	ALTER TABLE dbo.TB_REVIEW ADD
		ENABLE_ARMS bit NULL
GO
IF COL_LENGTH('dbo.TB_REVIEW','ENABLE_ARMS') IS NULL
	ALTER TABLE dbo.TB_REVIEW SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GO

use [Reviewer]
GO
update TB_REVIEW
set ENABLE_ARMS = 'true'
where REVIEW_ID = 11177 or REVIEW_ID = 10951 or REVIEW_ID = 7 OR REVIEW_ID = 247
go