USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ItemTimepointList]    Script Date: 09/02/2021 14:04:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_ItemTimepointList]
(
    @REVIEW_ID INT,
    @ITEM_ID BIGINT
)
As

SET NOCOUNT ON

    SELECT TB_ITEM_TIMEPOINT.ITEM_ID, ITEM_TIMEPOINT_ID, TIMEPOINT_VALUE, TIMEPOINT_METRIC,
        CASE
            WHEN TIMEPOINT_METRIC = 'seconds' THEN DATEADD(SECOND, TIMEPOINT_VALUE, GETDATE())
            WHEN TIMEPOINT_METRIC = 'minutes' THEN DATEADD(MINUTE, TIMEPOINT_VALUE, GETDATE())
            WHEN TIMEPOINT_METRIC = 'hours' THEN DATEADD(HOUR, TIMEPOINT_VALUE, GETDATE())
            WHEN TIMEPOINT_METRIC = 'days' THEN DATEADD(DAY, TIMEPOINT_VALUE, GETDATE())
            WHEN TIMEPOINT_METRIC = 'weeks' THEN DATEADD(WEEK, TIMEPOINT_VALUE, GETDATE())
            WHEN TIMEPOINT_METRIC = 'months' THEN DATEADD(MONTH, TIMEPOINT_VALUE, GETDATE())
            WHEN TIMEPOINT_METRIC = 'years' THEN DATEADD(YEAR, TIMEPOINT_VALUE, GETDATE())
        END AS TimepointVal
    
    FROM TB_ITEM_TIMEPOINT
        INNER JOIN TB_ITEM_REVIEW ON TB_ITEM_REVIEW.ITEM_ID = TB_ITEM_TIMEPOINT.ITEM_ID
        WHERE REVIEW_ID = @REVIEW_ID
        AND TB_ITEM_TIMEPOINT.ITEM_ID = @ITEM_ID
        ORDER BY TimepointVal

SET NOCOUNT OFF
GO