USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_AttributeSetUpdate]    Script Date: 28/01/2022 17:44:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   procedure [dbo].[st_AttributeSetUpdate]
(
	@ATTRIBUTE_SET_ID BIGINT,
	@SET_ID INT,
	@ATTRIBUTE_ID BIGINT,
	@PARENT_ATTRIBUTE_ID BIGINT,
	@ATTRIBUTE_TYPE_ID INT,
	@ATTRIBUTE_SET_DESC NVARCHAR(MAX),
	@ATTRIBUTE_ORDER INT,
	@ATTRIBUTE_NAME NVARCHAR(255),
	@ATTRIBUTE_DESC NVARCHAR(2000),
	@CONTACT_ID INT -- not used yet - maybe for authorisation,
	,@REVIEW_ID INT
	,@Ext_URL nvarchar(2048) = ''
	,@Ext_Type nvarchar(100) = ''
	,@ORIGINAL_ATTRIBUTE_ID bigint = null
)

As

SET NOCOUNT ON

declare @check int = 0

set @check = (select count (tas.ATTRIBUTE_ID) from TB_ATTRIBUTE_SET tas
				inner join TB_REVIEW_SET rs on tas.SET_ID = rs.SET_ID 
					and tas.ATTRIBUTE_ID = @ATTRIBUTE_ID
					and rs.REVIEW_ID = @REVIEW_ID
					and tas.ATTRIBUTE_SET_ID = @ATTRIBUTE_SET_ID
			)

if(@check != 1) return


	UPDATE TB_ATTRIBUTE
		SET ATTRIBUTE_NAME = @ATTRIBUTE_NAME, ATTRIBUTE_DESC = @ATTRIBUTE_DESC,
			Ext_Type = @Ext_Type, Ext_URL = @Ext_URL, ORIGINAL_ATTRIBUTE_ID = @ORIGINAL_ATTRIBUTE_ID
		WHERE ATTRIBUTE_ID = @ATTRIBUTE_ID

	UPDATE TB_ATTRIBUTE_SET
		SET SET_ID = @SET_ID, PARENT_ATTRIBUTE_ID = @PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID = @ATTRIBUTE_TYPE_ID,
			ATTRIBUTE_SET_DESC = @ATTRIBUTE_SET_DESC, ATTRIBUTE_ORDER = @ATTRIBUTE_ORDER
		WHERE ATTRIBUTE_SET_ID = @ATTRIBUTE_SET_ID


SET NOCOUNT OFF
GO