/****** Object:  Table [dbo].[tb_REVIEW_JOB]    Script Date: 2/10/2019 10:01:39 AM ******/

/*
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = tb_REVIEW_JOB))
BEGIN

CREATE TABLE [dbo].[tb_REVIEW_JOB](
	[REVIEW_JOB_ID] [int] IDENTITY(1,1) NOT NULL,
	[REVIEW_ID] [int] NULL,
	[CONTACT_ID] [int] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[JOB_TYPE] [nvarchar](50) NULL,
	[CURRENT_STATE] [nvarchar](50) NULL,
	[SUCCESS] [int] NULL,
 CONSTRAINT [PK_tb_REVIEW_JOB] PRIMARY KEY CLUSTERED 
(
	[REVIEW_JOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[tb_REVIEW_JOB]  WITH CHECK ADD  CONSTRAINT [FK_tb_REVIEW_JOB_TB_CONTACT] FOREIGN KEY([CONTACT_ID])
REFERENCES [dbo].[TB_CONTACT] ([CONTACT_ID])
ALTER TABLE [dbo].[tb_REVIEW_JOB] CHECK CONSTRAINT [FK_tb_REVIEW_JOB_TB_CONTACT]
ALTER TABLE [dbo].[tb_REVIEW_JOB]  WITH CHECK ADD  CONSTRAINT [FK_tb_REVIEW_JOB_TB_REVIEW] FOREIGN KEY([REVIEW_ID])
REFERENCES [dbo].[TB_REVIEW] ([REVIEW_ID])
ALTER TABLE [dbo].[tb_REVIEW_JOB] CHECK CONSTRAINT [FK_tb_REVIEW_JOB_TB_REVIEW]
END -- CREATE TB_REVIEW_JOB

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TB_ITEM ADD
	SearchText nvarchar(500) NULL
GO
ALTER TABLE dbo.TB_ITEM SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190210-225706] ON [dbo].[TB_ITEM]
(
	[SearchText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

*/
