USE [Reviewer]
GO

/****** Object:  Table [dbo].[tb_REVIEW_JOB]    Script Date: 2/10/2019 10:01:39 AM ******/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = N'tb_REVIEW_JOB'))
BEGIN

CREATE TABLE [dbo].[tb_REVIEW_JOB](
	[REVIEW_JOB_ID] [int] IDENTITY(1,1) NOT NULL,
	[REVIEW_ID] [int] NULL,
	[CONTACT_ID] [int] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[JOB_TYPE] [nvarchar](50) NULL,
	[CURRENT_STATE] [nvarchar](50) NULL,
	[SUCCESS] [int] NULL,
 CONSTRAINT [PK_tb_REVIEW_JOB] PRIMARY KEY CLUSTERED 
(
	[REVIEW_JOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[tb_REVIEW_JOB]  WITH CHECK ADD  CONSTRAINT [FK_tb_REVIEW_JOB_TB_CONTACT] FOREIGN KEY([CONTACT_ID])
REFERENCES [dbo].[TB_CONTACT] ([CONTACT_ID])
ALTER TABLE [dbo].[tb_REVIEW_JOB] CHECK CONSTRAINT [FK_tb_REVIEW_JOB_TB_CONTACT]
ALTER TABLE [dbo].[tb_REVIEW_JOB]  WITH CHECK ADD  CONSTRAINT [FK_tb_REVIEW_JOB_TB_REVIEW] FOREIGN KEY([REVIEW_ID])
REFERENCES [dbo].[TB_REVIEW] ([REVIEW_ID])
ALTER TABLE [dbo].[tb_REVIEW_JOB] CHECK CONSTRAINT [FK_tb_REVIEW_JOB_TB_REVIEW]
END -- CREATE TB_REVIEW_JOB


GO
IF COL_LENGTH('dbo.TB_ITEM', 'SearchText') IS NULL
begin
BEGIN TRANSACTION
ALTER TABLE dbo.TB_ITEM ADD
	SearchText nvarchar(500) NULL

ALTER TABLE dbo.TB_ITEM SET (LOCK_ESCALATION = TABLE)
COMMIT

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190210-225706] ON [dbo].[TB_ITEM]
(
	[SearchText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

END
GO

IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = N'TB_ITEM_TIMEPOINT'))
begin

CREATE TABLE [dbo].[TB_ITEM_TIMEPOINT](
	[ITEM_TIMEPOINT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ITEM_ID] [bigint] NOT NULL,
	[TIMEPOINT_VALUE] [float] NOT NULL,
	[TIMEPOINT_METRIC] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TB_ITEM_TIMEPOINT] PRIMARY KEY CLUSTERED 
(
	[ITEM_TIMEPOINT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT]  WITH CHECK ADD  CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[TB_ITEM] ([ITEM_ID])


ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT] CHECK CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM]


ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT]  WITH CHECK ADD  CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM_TIMEPOINT] FOREIGN KEY([ITEM_TIMEPOINT_ID])
REFERENCES [dbo].[TB_ITEM_TIMEPOINT] ([ITEM_TIMEPOINT_ID])

ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT] CHECK CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM_TIMEPOINT]
end
go


--Sergio edit START
IF COL_LENGTH('dbo.TB_ITEM_OUTCOME', 'ITEM_TIMEPOINT_ID') IS NULL
begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION

ALTER TABLE dbo.TB_ITEM_OUTCOME ADD
	ITEM_TIMEPOINT_ID bigint NULL,
	ITEM_ARM_ID_GRP1 bigint NULL,
	ITEM_ARM_ID_GRP2 bigint NULL



ALTER TABLE dbo.TB_ITEM_OUTCOME SET (LOCK_ESCALATION = TABLE)

COMMIT
END
GO
--Sergio edit END



IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[st_ItemTimepointUpdate]') AND type in (N'P', N'PC'))

DROP PROCEDURE [dbo].[st_ItemTimepointUpdate]

GO

/****** Object:  StoredProcedure [dbo].[st_ItemTimepointUpdate]    Script Date: 07/03/2019 13:03:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[st_ItemTimepointUpdate]
(
	@ITEM_TIMEPOINT_ID BIGINT
,	@TIMEPOINT_VALUE FLOAT
,	@TIMEPOINT_METRIC VARCHAR(50)
)

As

SET NOCOUNT ON

	UPDATE TB_ITEM_TIMEPOINT
		SET TIMEPOINT_VALUE = @TIMEPOINT_VALUE,
			TIMEPOINT_METRIC = @TIMEPOINT_METRIC
		WHERE ITEM_TIMEPOINT_ID = @ITEM_TIMEPOINT_ID

SET NOCOUNT OFF


GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[st_ItemTimepointList]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[st_ItemTimepointList]
GO

/****** Object:  StoredProcedure [dbo].[st_ItemTimepointList]    Script Date: 07/03/2019 13:03:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[st_ItemTimepointList]
(
	@REVIEW_ID INT,
	@ITEM_ID BIGINT
)

As

SET NOCOUNT ON

	SELECT TB_ITEM_TIMEPOINT.ITEM_ID, ITEM_TIMEPOINT_ID, TIMEPOINT_VALUE, TIMEPOINT_METRIC FROM TB_ITEM_TIMEPOINT
		INNER JOIN TB_ITEM_REVIEW ON TB_ITEM_REVIEW.ITEM_ID = TB_ITEM_TIMEPOINT.ITEM_ID
		WHERE REVIEW_ID = @REVIEW_ID
		AND TB_ITEM_TIMEPOINT.ITEM_ID = @ITEM_ID
		ORDER BY TIMEPOINT_VALUE

SET NOCOUNT OFF

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[st_ItemTimepointDelete]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[st_ItemTimepointDelete]
GO
/****** Object:  StoredProcedure [dbo].[st_ItemTimepointDelete]    Script Date: 07/03/2019 13:03:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[st_ItemTimepointDelete]
(
	@ITEM_TIMEPOINT_ID BIGINT
)

As

SET NOCOUNT ON
	UPDATE TB_ITEM_OUTCOME
		SET ITEM_TIMEPOINT_ID = NULL
		WHERE ITEM_TIMEPOINT_ID = @ITEM_TIMEPOINT_ID

	DELETE FROM TB_ITEM_TIMEPOINT
		WHERE ITEM_TIMEPOINT_ID = @ITEM_TIMEPOINT_ID

SET NOCOUNT OFF


GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[st_ItemTimepointCreate]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[st_ItemTimepointCreate]
GO

/****** Object:  StoredProcedure [dbo].[st_ItemTimepointCreate]    Script Date: 09/03/2019 22:47:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].st_ItemTimepointCreate
(
	@ITEM_ID BIGINT
,	@TIMEPOINT_VALUE FLOAT
,	@TIMEPOINT_METRIC varchar(50)
,	@NEW_ITEM_TIMEPOINT_ID BIGINT OUTPUT
)

As

SET NOCOUNT ON



	INSERT INTO TB_ITEM_TIMEPOINT(ITEM_ID, TIMEPOINT_VALUE, TIMEPOINT_METRIC)
	VALUES(@ITEM_ID, @TIMEPOINT_VALUE, @TIMEPOINT_METRIC)
		
	SET @NEW_ITEM_TIMEPOINT_ID = @@IDENTITY

SET NOCOUNT OFF

ALTER TABLE dbo.TB_ITEM_OUTCOME ADD
	ITEM_TIMEPOINT_ID bigint NULL,
	ITEM_ARM_ID_GRP1 bigint NULL,
	ITEM_ARM_ID_GRP2 bigint NULL
GO

USE [Reviewer]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[st_OutcomeItemList]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[st_OutcomeItemList]
GO

/****** Object:  StoredProcedure [dbo].[st_OutcomeItemList]    Script Date: 11/03/2019 08:49:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[st_OutcomeItemList]
(
	@REVIEW_ID INT,
	@ITEM_SET_ID BIGINT
)

As

SET NOCOUNT ON

SELECT OUTCOME_ID, SHORT_TITLE, TB_ITEM_OUTCOME.ITEM_SET_ID, OUTCOME_TYPE_ID, ITEM_ATTRIBUTE_ID_INTERVENTION,
	ITEM_ATTRIBUTE_ID_CONTROL, ITEM_ATTRIBUTE_ID_OUTCOME, OUTCOME_TITLE, OUTCOME_DESCRIPTION,
	DATA1, DATA2, DATA3, DATA4, DATA5, DATA6, DATA7, DATA8, DATA9, DATA10, DATA11, DATA12, DATA13, DATA14,
	A1.ATTRIBUTE_NAME AS INTERVENTION_TEXT,
	a2.ATTRIBUTE_NAME AS CONTROL_TEXT,
	a3.ATTRIBUTE_NAME AS OUTCOME_TEXT,
	0 as META_ANALYSIS_OUTCOME_ID -- Meta-analysis id. 0 as not selected
,	TB_ITEM_OUTCOME.ITEM_TIMEPOINT_ID
,	TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP1
,	TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP2
,	CONCAT(TB_ITEM_TIMEPOINT.TIMEPOINT_VALUE, ' ', TB_ITEM_TIMEPOINT.TIMEPOINT_METRIC) TimepointDisplayValue
,	arm1.ARM_NAME grp1ArmName
,	arm2.ARM_NAME grp2ArmName
FROM TB_ITEM_OUTCOME
INNER JOIN TB_ITEM_SET ON TB_ITEM_SET.ITEM_SET_ID = TB_ITEM_OUTCOME.ITEM_SET_ID
INNER JOIN TB_ITEM ON TB_ITEM.ITEM_ID = TB_ITEM_SET.ITEM_ID
left outer JOIN TB_ATTRIBUTE IA1 ON IA1.ATTRIBUTE_ID = TB_ITEM_OUTCOME.ITEM_ATTRIBUTE_ID_INTERVENTION
left outer JOIN TB_ATTRIBUTE A1 ON A1.ATTRIBUTE_ID = IA1.ATTRIBUTE_ID 
left outer JOIN TB_ATTRIBUTE IA2 ON IA2.ATTRIBUTE_ID = TB_ITEM_OUTCOME.ITEM_ATTRIBUTE_ID_CONTROL
left outer JOIN TB_ATTRIBUTE A2 ON A2.ATTRIBUTE_ID = IA2.ATTRIBUTE_ID
left outer JOIN TB_ATTRIBUTE IA3 ON IA3.ATTRIBUTE_ID = TB_ITEM_OUTCOME.ITEM_ATTRIBUTE_ID_OUTCOME
left outer JOIN TB_ATTRIBUTE A3 ON A3.ATTRIBUTE_ID = IA3.ATTRIBUTE_ID 
left outer join TB_ITEM_TIMEPOINT ON TB_ITEM_TIMEPOINT.ITEM_TIMEPOINT_ID = TB_ITEM_OUTCOME.ITEM_TIMEPOINT_ID
left outer join TB_ITEM_ARM arm1 ON arm1.ITEM_ARM_ID = TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP1
left outer join TB_ITEM_ARM arm2 on arm2.ITEM_ARM_ID = TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP2

WHERE TB_ITEM_OUTCOME.ITEM_SET_ID = @ITEM_SET_ID

SET NOCOUNT OFF
GO


/****** Object:  StoredProcedure [dbo].[st_OutcomeSingle]    Script Date: 11/03/2019 08:48:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[st_OutcomeSingle]
(
	@OUTCOME_ID INT
)

As

SET NOCOUNT ON

SELECT OUTCOME_ID, SHORT_TITLE, TB_ITEM_OUTCOME.ITEM_SET_ID, TB_ITEM_OUTCOME.OUTCOME_TYPE_ID, ITEM_ATTRIBUTE_ID_INTERVENTION,
	ITEM_ATTRIBUTE_ID_CONTROL, ITEM_ATTRIBUTE_ID_OUTCOME, OUTCOME_TITLE, OUTCOME_DESCRIPTION,
	DATA1, DATA2, DATA3, DATA4, DATA5, DATA6, DATA7, DATA8, DATA9, DATA10, DATA11, DATA12, DATA13, DATA14,
	A1.ATTRIBUTE_NAME AS INTERVENTION_TEXT,
	a2.ATTRIBUTE_NAME AS CONTROL_TEXT,
	a3.ATTRIBUTE_NAME AS OUTCOME_TEXT,
	0 as META_ANALYSIS_OUTCOME_ID, -- Meta-analysis id. 0 as not selected
	OUTCOME_TYPE_NAME
	,	TB_ITEM_OUTCOME.ITEM_TIMEPOINT_ID
,	TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP1
,	TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP2
,	CONCAT(TB_ITEM_TIMEPOINT.TIMEPOINT_VALUE, ' ', TB_ITEM_TIMEPOINT.TIMEPOINT_METRIC) TimepointDisplayValue
,	arm1.ARM_NAME grp1ArmName
,	arm2.ARM_NAME grp2ArmName
FROM TB_ITEM_OUTCOME
INNER JOIN TB_ITEM_SET ON TB_ITEM_SET.ITEM_SET_ID = TB_ITEM_OUTCOME.ITEM_SET_ID
INNER JOIN TB_ITEM ON TB_ITEM.ITEM_ID = TB_ITEM_SET.ITEM_ID
INNER JOIN TB_OUTCOME_TYPE ON TB_OUTCOME_TYPE.OUTCOME_TYPE_ID = TB_ITEM_OUTCOME.OUTCOME_TYPE_ID
left outer JOIN TB_ATTRIBUTE IA1 ON IA1.ATTRIBUTE_ID = TB_ITEM_OUTCOME.ITEM_ATTRIBUTE_ID_INTERVENTION
left outer JOIN TB_ATTRIBUTE A1 ON A1.ATTRIBUTE_ID = IA1.ATTRIBUTE_ID 
left outer JOIN TB_ATTRIBUTE IA2 ON IA2.ATTRIBUTE_ID = TB_ITEM_OUTCOME.ITEM_ATTRIBUTE_ID_CONTROL
left outer JOIN TB_ATTRIBUTE A2 ON A2.ATTRIBUTE_ID = IA2.ATTRIBUTE_ID
left outer JOIN TB_ATTRIBUTE IA3 ON IA3.ATTRIBUTE_ID = TB_ITEM_OUTCOME.ITEM_ATTRIBUTE_ID_OUTCOME
left outer JOIN TB_ATTRIBUTE A3 ON A3.ATTRIBUTE_ID = IA3.ATTRIBUTE_ID
left outer join TB_ITEM_TIMEPOINT ON TB_ITEM_TIMEPOINT.ITEM_TIMEPOINT_ID = TB_ITEM_OUTCOME.ITEM_TIMEPOINT_ID
left outer join TB_ITEM_ARM arm1 ON arm1.ITEM_ARM_ID = TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP1
left outer join TB_ITEM_ARM arm2 on arm2.ITEM_ARM_ID = TB_ITEM_OUTCOME.ITEM_ARM_ID_GRP2

WHERE TB_ITEM_OUTCOME.OUTCOME_ID = @OUTCOME_ID


SET NOCOUNT OFF


GO
/****** Object:  StoredProcedure [dbo].[st_OutcomeItemUpdate]    Script Date: 11/03/2019 10:29:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_OutcomeItemUpdate]
(
	@OUTCOME_ID INT,
	@OUTCOME_TYPE_ID INT,
	@ITEM_ATTRIBUTE_ID_INTERVENTION BIGINT,
	@ITEM_ATTRIBUTE_ID_CONTROL BIGINT,
	@ITEM_ATTRIBUTE_ID_OUTCOME BIGINT,
	@OUTCOME_TITLE NVARCHAR(255),
	@OUTCOME_DESCRIPTION NVARCHAR(4000),
	@DATA1 DECIMAL (18, 9),
	@DATA2 DECIMAL (18, 9),
	@DATA3 DECIMAL (18, 9),
	@DATA4 DECIMAL (18, 9),
	@DATA5 DECIMAL (18, 9),
	@DATA6 DECIMAL (18, 9),
	@DATA7 DECIMAL (18, 9),
	@DATA8 DECIMAL (18, 9),
	@DATA9 DECIMAL (18, 9),
	@DATA10 DECIMAL (18, 9),
	@DATA11 DECIMAL (18, 9),
	@DATA12 DECIMAL (18, 9),
	@DATA13 DECIMAL (18, 9),
	@DATA14 DECIMAL (18, 9),
	@ITEM_TIMEPOINT_ID BIGINT,
	@ITEM_ARM_ID_GRP1 BIGINT,
	@ITEM_ARM_ID_GRP2 BIGINT
)

As

SET NOCOUNT ON
	
	UPDATE TB_ITEM_OUTCOME SET
	OUTCOME_TYPE_ID = @OUTCOME_TYPE_ID,
	ITEM_ATTRIBUTE_ID_INTERVENTION = @ITEM_ATTRIBUTE_ID_INTERVENTION,
	ITEM_ATTRIBUTE_ID_CONTROL = @ITEM_ATTRIBUTE_ID_CONTROL,
	ITEM_ATTRIBUTE_ID_OUTCOME = @ITEM_ATTRIBUTE_ID_OUTCOME,
	OUTCOME_TITLE = @OUTCOME_TITLE,
	OUTCOME_DESCRIPTION = @OUTCOME_DESCRIPTION,
	DATA1 = @DATA1,
	DATA2 = @DATA2,
	DATA3 = @DATA3,
	DATA4 = @DATA4,
	DATA5 = @DATA5,
	DATA6 = @DATA6,
	DATA7 = @DATA7,
	DATA8 = @DATA8,
	DATA9 = @DATA9,
	DATA10 = @DATA10,
	DATA11 = @DATA11,
	DATA12 = @DATA12,
	DATA13 = @DATA13,
	DATA14 = @DATA14,
	ITEM_TIMEPOINT_ID = @ITEM_TIMEPOINT_ID,
	ITEM_ARM_ID_GRP1 = @ITEM_ARM_ID_GRP1,
	ITEM_ARM_ID_GRP2 = @ITEM_ARM_ID_GRP2
	
	WHERE OUTCOME_ID = @OUTCOME_ID

SET NOCOUNT OFF


GO
/****** Object:  StoredProcedure [dbo].[st_OutcomeItemInsert]    Script Date: 11/03/2019 10:29:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_OutcomeItemInsert]
(
	@ITEM_SET_ID BIGINT,
	@OUTCOME_TYPE_ID INT = 1,
	@ITEM_ATTRIBUTE_ID_INTERVENTION BIGINT,
	@ITEM_ATTRIBUTE_ID_CONTROL BIGINT,
	@ITEM_ATTRIBUTE_ID_OUTCOME BIGINT,
	@OUTCOME_TITLE NVARCHAR(255),
	@OUTCOME_DESCRIPTION NVARCHAR(4000),
	@DATA1 DECIMAL (18, 9),
	@DATA2 DECIMAL (18, 9),
	@DATA3 DECIMAL (18, 9),
	@DATA4 DECIMAL (18, 9),
	@DATA5 DECIMAL (18, 9),
	@DATA6 DECIMAL (18, 9),
	@DATA7 DECIMAL (18, 9),
	@DATA8 DECIMAL (18, 9),
	@DATA9 DECIMAL (18, 9),
	@DATA10 DECIMAL (18, 9),
	@DATA11 DECIMAL (18, 9),
	@DATA12 DECIMAL (18, 9),
	@DATA13 DECIMAL (18, 9),
	@DATA14 DECIMAL (18, 9),
	@ITEM_TIMEPOINT_ID BIGINT,
	@ITEM_ARM_ID_GRP1 BIGINT,
	@ITEM_ARM_ID_GRP2 BIGINT,
	@NEW_OUTCOME_ID INT OUTPUT
)

As

SET NOCOUNT ON
	
	INSERT INTO TB_ITEM_OUTCOME
	(	ITEM_SET_ID
	,	OUTCOME_TYPE_ID
	,	ITEM_ATTRIBUTE_ID_INTERVENTION
	,	ITEM_ATTRIBUTE_ID_CONTROL
	,	ITEM_ATTRIBUTE_ID_OUTCOME
	,	OUTCOME_TITLE
	,	OUTCOME_DESCRIPTION
	,	DATA1
	,	DATA2
	,	DATA3
	,	DATA4
	,	DATA5
	,	DATA6
	,	DATA7
	,	DATA8
	,	DATA9
	,	DATA10
	,	DATA11
	,	DATA12
	,	DATA13
	,	DATA14
	,	ITEM_TIMEPOINT_ID
	,	ITEM_ARM_ID_GRP1
	,	ITEM_ARM_ID_GRP2
	)	
	VALUES
	(
		@ITEM_SET_ID
	,	@OUTCOME_TYPE_ID
	,	@ITEM_ATTRIBUTE_ID_INTERVENTION
	,	@ITEM_ATTRIBUTE_ID_CONTROL
	,	@ITEM_ATTRIBUTE_ID_OUTCOME
	,	@OUTCOME_TITLE
	,	@OUTCOME_DESCRIPTION
	,	@DATA1
	,	@DATA2
	,	@DATA3
	,	@DATA4
	,	@DATA5
	,	@DATA6
	,	@DATA7
	,	@DATA8
	,	@DATA9
	,	@DATA10
	,	@DATA11
	,	@DATA12
	,	@DATA13
	,	@DATA14
	,	@ITEM_TIMEPOINT_ID
	,	@ITEM_ARM_ID_GRP1
	,	@ITEM_ARM_ID_GRP2
	)
	-- Get the identity and return it
	SET @NEW_OUTCOME_ID = @@identity

SET NOCOUNT OFF


GO
/****** Object:  StoredProcedure [dbo].[st_OutcomeList]    Script Date: 11/03/2019 12:50:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_OutcomeList]
(
	@REVIEW_ID INT,
	@META_ANALYSIS_ID INT,
	@QUESTIONS nvarchar(max) = '',
	@ANSWERS nvarchar(max) = ''
	/*@SET_ID BIGINT,
	@ITEM_ATTRIBUTE_ID_INTERVENTION BIGINT = NULL,
	@ITEM_ATTRIBUTE_ID_CONTROL BIGINT = NULL,
	@ITEM_ATTRIBUTE_ID_OUTCOME BIGINT = NULL,
	@ATTRIBUTE_ID BIGINT = NULL,
	
	
	@VARIABLES NVARCHAR(MAX) = NULL,
	@ANSWERS NVARCHAR(MAX) = '',
	@QUESTIONS NVARCHAR(MAX) = ''*/
)

As

SET NOCOUNT ON
	SELECT distinct tio.OUTCOME_ID, tio.ITEM_SET_ID, OUTCOME_TYPE_ID, ITEM_ATTRIBUTE_ID_INTERVENTION,
	ITEM_ATTRIBUTE_ID_CONTROL, ITEM_ATTRIBUTE_ID_OUTCOME, OUTCOME_TITLE, SHORT_TITLE, OUTCOME_DESCRIPTION,
	DATA1, DATA2, DATA3, DATA4, DATA5, DATA6, DATA7, DATA8, DATA9, DATA10, DATA11, DATA12, DATA13, DATA14,
	TB_META_ANALYSIS_OUTCOME.META_ANALYSIS_OUTCOME_ID, tis.ITEM_SET_ID, TB_ITEM_ATTRIBUTE.ITEM_ID,
	A1.ATTRIBUTE_NAME INTERVENTION_TEXT, A2.ATTRIBUTE_NAME CONTROL_TEXT, A3.ATTRIBUTE_NAME OUTCOME_TEXT
	,	tio.ITEM_TIMEPOINT_ID
,	tio.ITEM_ARM_ID_GRP1
,	tio.ITEM_ARM_ID_GRP2
,	CONCAT(TB_ITEM_TIMEPOINT.TIMEPOINT_VALUE, ' ', TB_ITEM_TIMEPOINT.TIMEPOINT_METRIC) TimepointDisplayValue
,	arm1.ARM_NAME grp1ArmName
,	arm2.ARM_NAME grp2ArmName
	FROM TB_ITEM_OUTCOME tio
	inner join TB_ITEM_SET tis on tis.ITEM_SET_ID = tio.ITEM_SET_ID
		AND tis.IS_COMPLETED = 1
	inner join TB_REVIEW_SET rs on rs.REVIEW_ID = @REVIEW_ID and rs.SET_ID = tis.SET_ID
	inner join TB_ITEM_REVIEW on tb_item_review.ITEM_ID = tis.ITEM_ID AND TB_ITEM_REVIEW.REVIEW_ID = @REVIEW_ID
	inner JOIN TB_ITEM_ATTRIBUTE ON TB_ITEM_ATTRIBUTE.ITEM_SET_ID = tis.ITEM_SET_ID
	inner join TB_ITEM on TB_ITEM.ITEM_ID = tis.ITEM_ID
	LEFT OUTER JOIN TB_META_ANALYSIS_OUTCOME ON TB_META_ANALYSIS_OUTCOME.OUTCOME_ID = tio.OUTCOME_ID
		AND TB_META_ANALYSIS_OUTCOME.META_ANALYSIS_ID = @META_ANALYSIS_ID
	left outer JOIN TB_ATTRIBUTE A1 ON A1.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_INTERVENTION 
	left outer JOIN TB_ATTRIBUTE A2 ON A2.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_CONTROL
	left outer JOIN TB_ATTRIBUTE A3 ON A3.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_OUTCOME
	left outer join TB_ITEM_TIMEPOINT ON TB_ITEM_TIMEPOINT.ITEM_TIMEPOINT_ID = tio.ITEM_TIMEPOINT_ID
	left outer join TB_ITEM_ARM arm1 ON arm1.ITEM_ARM_ID = tio.ITEM_ARM_ID_GRP1
	left outer join TB_ITEM_ARM arm2 on arm2.ITEM_ARM_ID = tio.ITEM_ARM_ID_GRP2

	--second sets of results, the answers
	--we need to get these, even if empty, so that we always get a reader
	
	IF (@QUESTIONS is not null AND @QUESTIONS != '')
	BEGIN
		declare @QT table ( AttID bigint primary key)
		insert into @QT select qss.value from dbo.fn_Split_int(@QUESTIONS, ',') as qss
		select tio.OUTCOME_ID, tio.OUTCOME_TITLE, tis.ITEM_ID 
			, ATTRIBUTE_NAME as Codename
			, a.ATTRIBUTE_ID as ATTRIBUTE_ID
			, tas.PARENT_ATTRIBUTE_ID
		from TB_ITEM_OUTCOME tio 
		inner join TB_ITEM_SET tis on tio.ITEM_SET_ID = tis.ITEM_SET_ID and tis.IS_COMPLETED = 1
		inner join TB_ITEM_SET tis2 on tis.ITEM_ID = tis2.ITEM_ID
		inner join TB_ITEM_ATTRIBUTE tia on tis2.ITEM_SET_ID = tia.ITEM_SET_ID
		inner join TB_REVIEW_SET rs on tis2.SET_ID = rs.SET_ID and rs.REVIEW_ID = @REVIEW_ID
		inner join TB_ATTRIBUTE_SET tas on tas.ATTRIBUTE_ID = tia.ATTRIBUTE_ID
		inner join @QT Qs on Qs.AttID = tas.PARENT_ATTRIBUTE_ID
		inner join TB_ATTRIBUTE a on tas.ATTRIBUTE_ID = a.ATTRIBUTE_ID
		order by OUTCOME_ID, tas.PARENT_ATTRIBUTE_ID, tas.ATTRIBUTE_ORDER, a.ATTRIBUTE_ID
	END
	ELSE
	BEGIN
	select tio.OUTCOME_ID, tio.OUTCOME_TITLE, tis.ITEM_ID, 
		tio.OUTCOME_TITLE as Codename
		, tio.ITEM_ATTRIBUTE_ID_CONTROL as ATTRIBUTE_ID, tio.ITEM_ATTRIBUTE_ID_CONTROL as PARENT_ATTRIBUTE_ID
		from TB_ITEM_OUTCOME tio
		inner join TB_ITEM_SET tis on tio.ITEM_SET_ID = tis.ITEM_SET_ID and 1=0
	END


	IF (@ANSWERS is not null AND @ANSWERS != '')
	BEGIN
	--third set of results, the questions
	declare @AT table ( AttID bigint primary key)
	insert into @AT select qss.value from dbo.fn_Split_int(@ANSWERS, ',') as qss
	select tio.OUTCOME_ID, tio.OUTCOME_TITLE, tis.ITEM_ID, 
		--(Select top(1) a.ATTRIBUTE_NAME from @AT 
		--inner join TB_ATTRIBUTE_SET tas on tas.ATTRIBUTE_ID = AttID
		--inner join TB_ATTRIBUTE a on tas.ATTRIBUTE_ID = a.ATTRIBUTE_ID
		--inner join TB_ITEM_ATTRIBUTE tia on a.ATTRIBUTE_ID = tia.ATTRIBUTE_ID
		--inner join TB_ITEM_SET tis1 on tia.ITEM_SET_ID = tis1.ITEM_SET_ID and tis1.IS_COMPLETED = 1 and tis.ITEM_ID = tis1.ITEM_ID
		--inner join TB_REVIEW_SET rs1 on tis1.SET_ID = rs1.SET_ID and rs1.REVIEW_ID = @REVIEW_ID
		--order by tas.ATTRIBUTE_ORDER ) as Codename
		tia.ATTRIBUTE_ID, a.ATTRIBUTE_NAME
	from TB_ITEM_OUTCOME tio 
	inner join TB_ITEM_SET tis on tio.ITEM_SET_ID = tis.ITEM_SET_ID and tis.IS_COMPLETED = 1
	inner join TB_REVIEW_SET rs on tis.SET_ID = rs.SET_ID and rs.REVIEW_ID = @REVIEW_ID
	inner join TB_ITEM_SET tis2 on tis.ITEM_ID = tis2.ITEM_ID and tis2.IS_COMPLETED = 1
	inner join TB_ATTRIBUTE_SET tas on tis2.SET_ID = tas.SET_ID
	inner join TB_ITEM_ATTRIBUTE tia on tis2.ITEM_ID = tia.ITEM_ID and tas.ATTRIBUTE_ID = tia.ATTRIBUTE_ID
	inner join @AT on AttID = tia.ATTRIBUTE_ID
	inner join TB_ATTRIBUTE a on tia.ATTRIBUTE_ID = a.ATTRIBUTE_ID
	order by OUTCOME_ID
	END
	ELSE
	BEGIN
		select tio.OUTCOME_ID, tio.OUTCOME_TITLE, tis.ITEM_ID, 
		tio.ITEM_ATTRIBUTE_ID_CONTROL as ATTRIBUTE_ID, tio.OUTCOME_TITLE as ATTRIBUTE_NAME
	from TB_ITEM_OUTCOME tio inner join TB_ITEM_SET tis on tio.ITEM_SET_ID = tis.ITEM_SET_ID and 1=0
	
	END
	



--DECLARE @START_TEXT NVARCHAR(MAX) = N' SELECT distinct tio.OUTCOME_ID, tio.ITEM_SET_ID, OUTCOME_TYPE_ID, ITEM_ATTRIBUTE_ID_INTERVENTION,
--	ITEM_ATTRIBUTE_ID_CONTROL, ITEM_ATTRIBUTE_ID_OUTCOME, OUTCOME_TITLE, SHORT_TITLE, OUTCOME_DESCRIPTION,
--	DATA1, DATA2, DATA3, DATA4, DATA5, DATA6, DATA7, DATA8, DATA9, DATA10, DATA11, DATA12, DATA13, DATA14,
--	TB_META_ANALYSIS_OUTCOME.META_ANALYSIS_OUTCOME_ID, TB_ITEM_SET.ITEM_SET_ID, TB_ITEM_ATTRIBUTE.ITEM_ID,
--	A1.ATTRIBUTE_NAME INTERVENTION_TEXT, A2.ATTRIBUTE_NAME CONTROL_TEXT, A3.ATTRIBUTE_NAME OUTCOME_TEXT'
	
--DECLARE @END_TEXT NVARCHAR(MAX) = N' FROM TB_ITEM_OUTCOME tio

--	inner join TB_ITEM_SET on tb_item_set.ITEM_SET_ID = tio.ITEM_SET_ID
--		AND TB_ITEM_SET.IS_COMPLETED = ''TRUE''
--	inner join TB_ITEM_REVIEW on tb_item_review.ITEM_ID = tb_item_set.ITEM_ID AND TB_ITEM_REVIEW.REVIEW_ID = @REVIEW_ID
--	inner JOIN TB_ITEM_ATTRIBUTE ON TB_ITEM_ATTRIBUTE.ITEM_SET_ID = tb_item_set.ITEM_SET_ID
--	inner join TB_ITEM on TB_ITEM.ITEM_ID = TB_ITEM_SET.ITEM_ID
	
--	LEFT OUTER JOIN TB_META_ANALYSIS_OUTCOME ON TB_META_ANALYSIS_OUTCOME.OUTCOME_ID = tio.OUTCOME_ID
--		AND TB_META_ANALYSIS_OUTCOME.META_ANALYSIS_ID = @META_ANALYSIS_ID
		
--	left outer JOIN TB_ATTRIBUTE A1 ON A1.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_INTERVENTION 
--	left outer JOIN TB_ATTRIBUTE A2 ON A2.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_CONTROL
--	left outer JOIN TB_ATTRIBUTE A3 ON A3.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_OUTCOME'
	
--DECLARE @QUERY NVARCHAR(MAX) = @VARIABLES + @START_TEXT + @ANSWERS + @QUESTIONS + @END_TEXT
	
--EXEC (@QUERY)

--/*
--SELECT distinct tio.OUTCOME_ID, SHORT_TITLE, tio.ITEM_SET_ID, OUTCOME_TYPE_ID, ITEM_ATTRIBUTE_ID_INTERVENTION,
--	ITEM_ATTRIBUTE_ID_CONTROL, ITEM_ATTRIBUTE_ID_OUTCOME, OUTCOME_TITLE, OUTCOME_DESCRIPTION,
--	DATA1, DATA2, DATA3, DATA4, DATA5, DATA6, DATA7, DATA8, DATA9, DATA10, DATA11, DATA12, DATA13, DATA14,
--	TB_META_ANALYSIS_OUTCOME.META_ANALYSIS_OUTCOME_ID, TB_ITEM_SET.ITEM_SET_ID,
--	TB_ITEM_ATTRIBUTE.ITEM_ID, A1.ATTRIBUTE_NAME INTERVENTION_TEXT, A2.ATTRIBUTE_NAME CONTROL_TEXT,
--		A3.ATTRIBUTE_NAME OUTCOME_TEXT
	
--	FROM TB_ITEM_OUTCOME tio

--	inner join TB_ITEM_SET on tb_item_set.ITEM_SET_ID = tio.ITEM_SET_ID
--		AND TB_ITEM_SET.IS_COMPLETED = 'TRUE'
--	inner join TB_ITEM_REVIEW on tb_item_review.ITEM_ID = tb_item_set.ITEM_ID
--	inner JOIN TB_ITEM_ATTRIBUTE ON TB_ITEM_ATTRIBUTE.ITEM_SET_ID = tb_item_set.ITEM_SET_ID
--	inner join TB_ITEM on TB_ITEM.ITEM_ID = TB_ITEM_SET.ITEM_ID
	
--	LEFT OUTER JOIN TB_META_ANALYSIS_OUTCOME ON TB_META_ANALYSIS_OUTCOME.OUTCOME_ID = tio.OUTCOME_ID
--		AND TB_META_ANALYSIS_OUTCOME.META_ANALYSIS_ID = @META_ANALYSIS_ID
		
--	left outer JOIN TB_ATTRIBUTE A1 ON A1.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_INTERVENTION 
--	left outer JOIN TB_ATTRIBUTE A2 ON A2.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_CONTROL
--	left outer JOIN TB_ATTRIBUTE A3 ON A3.ATTRIBUTE_ID = tio.ITEM_ATTRIBUTE_ID_OUTCOME
	
--	WHERE TB_ITEM_REVIEW.REVIEW_ID = @REVIEW_ID
--	AND (@ITEM_ATTRIBUTE_ID_INTERVENTION = 0 OR (ITEM_ATTRIBUTE_ID_INTERVENTION = @ITEM_ATTRIBUTE_ID_INTERVENTION))
--	AND (@ITEM_ATTRIBUTE_ID_CONTROL = 0 OR (ITEM_ATTRIBUTE_ID_CONTROL = @ITEM_ATTRIBUTE_ID_CONTROL))
--	AND (@ITEM_ATTRIBUTE_ID_OUTCOME = 0 OR (ITEM_ATTRIBUTE_ID_OUTCOME = @ITEM_ATTRIBUTE_ID_OUTCOME))
--	--	AND (@ATTRIBUTE_ID IS NULL OR (TB_ITEM_ATTRIBUTE.ATTRIBUTE_ID = @ATTRIBUTE_ID))
--	--AND (
--	--	@ATTRIBUTE_ID IS NULL OR 
--	--		(
--	--		TB_ITEM_SET.ITEM_ID IN
--	--			( 
--	--			SELECT IA2.ITEM_ID FROM TB_ITEM_ATTRIBUTE IA2 
--	--			INNER JOIN TB_ITEM_SET IS2 ON IS2.ITEM_SET_ID = IA2.ITEM_SET_ID AND IS2.IS_COMPLETED = 'TRUE'
--	--			WHERE IA2.ATTRIBUTE_ID = @ATTRIBUTE_ID
--	--			)
--	--		)
--	--	)
--	--AND (--temp correction for before publishing: @ATTRIBUTE_ID is (because of bug) actually the item_attribute_id
--	--	@ATTRIBUTE_ID = 0 OR 
--	--		(
--	--		tio.OUTCOME_ID IN
--	--			( 
--	--				select tio2.OUTCOME_ID from TB_ATTRIBUTE_SET tas
--	--				inner join TB_ITEM_OUTCOME_ATTRIBUTE ioa on tas.ATTRIBUTE_ID = ioa.ATTRIBUTE_ID and tas.ATTRIBUTE_SET_ID = @ATTRIBUTE_ID
--	--				inner join TB_ITEM_OUTCOME tio2 on ioa.OUTCOME_ID = tio2.OUTCOME_ID
--	--			)
--	--		)
--	--	)--end of temp correction
--	AND (--real correction to use when bug is corrected in line 174 of dialogMetaAnalysisSetup.xaml.cs
--		@ATTRIBUTE_ID = 0 OR 
--			(
--			tio.OUTCOME_ID IN 
--				( 
--					select tio2.OUTCOME_ID from TB_ITEM_OUTCOME_ATTRIBUTE ioa  
--					inner join TB_ITEM_OUTCOME tio2 on ioa.OUTCOME_ID = tio2.OUTCOME_ID and ioa.ATTRIBUTE_ID = @ATTRIBUTE_ID
--				)
--			)
--		)--end of real correction
--	AND (@SET_ID = 0 OR (TB_ITEM_SET.SET_ID = @SET_ID))
	
--	--order by TB_ITEM_ATTRIBUTE.ATTRIBUTE_ID
--*/
SET NOCOUNT OFF

GO

/****** Object:  StoredProcedure [dbo].[st_ItemArmDelete]    Script Date: 04/04/2019 08:28:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_ItemArmDelete]
(
	@ITEM_ARM_ID BIGINT
)

As

SET NOCOUNT ON
	DELETE FROM TB_ITEM_ATTRIBUTE where ITEM_ARM_ID = @ITEM_ARM_ID
	DELETE FROM TB_ITEM_ARM
		WHERE ITEM_ARM_ID = @ITEM_ARM_ID

	UPDATE TB_ITEM_OUTCOME
		SET ITEM_ARM_ID_GRP1 = NULL
		WHERE ITEM_ARM_ID_GRP1 = @ITEM_ARM_ID

	UPDATE TB_ITEM_OUTCOME
		SET ITEM_ARM_ID_GRP2 = NULL
		WHERE ITEM_ARM_ID_GRP2 = @ITEM_ARM_ID

SET NOCOUNT OFF

GO


/****** Object:  StoredProcedure [dbo].[st_ItemArmDeleteWarning]    Script Date: 04/04/2019 08:26:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[st_ItemArmDeleteWarning]
	@ITEM_ID BIGINT,
	@ARM_ID BIGINT,
	@NUM_CODINGS INT OUTPUT,
	@NUM_OUTCOMES INT OUTPUT,
	@REVIEW_ID INT
As

SET NOCOUNT ON

	SELECT @NUM_CODINGS = COUNT(DISTINCT TB_ITEM_ATTRIBUTE.ITEM_ATTRIBUTE_ID) FROM TB_ITEM_ATTRIBUTE
		INNER JOIN TB_ITEM_REVIEW ON TB_ITEM_REVIEW.ITEM_ID = TB_ITEM_ATTRIBUTE.ITEM_ID
			AND TB_ITEM_REVIEW.REVIEW_ID = @REVIEW_ID
			AND TB_ITEM_REVIEW.ITEM_ID = @ITEM_ID
		WHERE TB_ITEM_ATTRIBUTE.ITEM_ARM_ID = @ARM_ID

	SELECT @NUM_OUTCOMES = COUNT(DISTINCT ITO.OUTCOME_ID) FROM TB_ITEM_OUTCOME ITO
		WHERE ITO.ITEM_ARM_ID_GRP1 = @ARM_ID OR ITO.ITEM_ARM_ID_GRP2 = @ARM_ID

SET NOCOUNT OFF

GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[st_ItemTimepointDeleteWarning]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[st_ItemTimepointDeleteWarning]
GO
/****** Object:  StoredProcedure [dbo].[st_ItemTimepointDeleteWarning]    Script Date: 04/04/2019 08:26:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
create PROCEDURE [dbo].[st_ItemTimepointDeleteWarning]
	@ITEM_ID BIGINT,
	@TIMEPOINT_ID BIGINT,
	@NUM_OUTCOMES INT OUTPUT,
	@REVIEW_ID INT
As

SET NOCOUNT ON

	SELECT @NUM_OUTCOMES = COUNT(DISTINCT ITO.OUTCOME_ID) FROM TB_ITEM_OUTCOME ITO
		WHERE ITO.ITEM_TIMEPOINT_ID = @TIMEPOINT_ID

SET NOCOUNT OFF
GO