/****** Object:  Table [dbo].[tb_REVIEW_JOB]    Script Date: 2/10/2019 10:01:39 AM ******/


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = tb_REVIEW_JOB))
BEGIN

CREATE TABLE [dbo].[tb_REVIEW_JOB](
	[REVIEW_JOB_ID] [int] IDENTITY(1,1) NOT NULL,
	[REVIEW_ID] [int] NULL,
	[CONTACT_ID] [int] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[JOB_TYPE] [nvarchar](50) NULL,
	[CURRENT_STATE] [nvarchar](50) NULL,
	[SUCCESS] [int] NULL,
 CONSTRAINT [PK_tb_REVIEW_JOB] PRIMARY KEY CLUSTERED 
(
	[REVIEW_JOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[tb_REVIEW_JOB]  WITH CHECK ADD  CONSTRAINT [FK_tb_REVIEW_JOB_TB_CONTACT] FOREIGN KEY([CONTACT_ID])
REFERENCES [dbo].[TB_CONTACT] ([CONTACT_ID])
ALTER TABLE [dbo].[tb_REVIEW_JOB] CHECK CONSTRAINT [FK_tb_REVIEW_JOB_TB_CONTACT]
ALTER TABLE [dbo].[tb_REVIEW_JOB]  WITH CHECK ADD  CONSTRAINT [FK_tb_REVIEW_JOB_TB_REVIEW] FOREIGN KEY([REVIEW_ID])
REFERENCES [dbo].[TB_REVIEW] ([REVIEW_ID])
ALTER TABLE [dbo].[tb_REVIEW_JOB] CHECK CONSTRAINT [FK_tb_REVIEW_JOB_TB_REVIEW]
END -- CREATE TB_REVIEW_JOB

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TB_ITEM ADD
	SearchText nvarchar(500) NULL
GO
ALTER TABLE dbo.TB_ITEM SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20190210-225706] ON [dbo].[TB_ITEM]
(
	[SearchText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO



CREATE TABLE [dbo].[TB_ITEM_TIMEPOINT](
	[ITEM_TIMEPOINT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ITEM_ID] [bigint] NOT NULL,
	[TIMEPOINT_VALUE] [float] NOT NULL,
	[TIMEPOINT_METRIC] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TB_ITEM_TIMEPOINT] PRIMARY KEY CLUSTERED 
(
	[ITEM_TIMEPOINT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT]  WITH CHECK ADD  CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[TB_ITEM] ([ITEM_ID])
GO

ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT] CHECK CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM]
GO

ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT]  WITH CHECK ADD  CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM_TIMEPOINT] FOREIGN KEY([ITEM_TIMEPOINT_ID])
REFERENCES [dbo].[TB_ITEM_TIMEPOINT] ([ITEM_TIMEPOINT_ID])
GO

ALTER TABLE [dbo].[TB_ITEM_TIMEPOINT] CHECK CONSTRAINT [FK_TB_ITEM_TIMEPOINT_TB_ITEM_TIMEPOINT]
GO

GO
/****** Object:  StoredProcedure [dbo].[st_ItemTimepointUpdate]    Script Date: 07/03/2019 13:03:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[st_ItemTimepointUpdate]
(
	@ITEM_TIMEPOINT_ID BIGINT
,	@TIMEPOINT_VALUE FLOAT
,	@TIMEPOINT_METRIC VARCHAR(50)
)

As

SET NOCOUNT ON

	UPDATE TB_ITEM_TIMEPOINT
		SET TIMEPOINT_VALUE = @TIMEPOINT_VALUE,
			TIMEPOINT_METRIC = @TIMEPOINT_METRIC
		WHERE ITEM_TIMEPOINT_ID = @ITEM_TIMEPOINT_ID

SET NOCOUNT OFF


GO

/****** Object:  StoredProcedure [dbo].[st_ItemTimepointList]    Script Date: 07/03/2019 13:03:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[st_ItemTimepointList]
(
	@REVIEW_ID INT,
	@ITEM_ID BIGINT
)

As

SET NOCOUNT ON

	SELECT TB_ITEM_TIMEPOINT.ITEM_ID, ITEM_TIMEPOINT_ID, TIMEPOINT_VALUE, TIMEPOINT_METRIC FROM TB_ITEM_TIMEPOINT
		INNER JOIN TB_ITEM_REVIEW ON TB_ITEM_REVIEW.ITEM_ID = TB_ITEM_TIMEPOINT.ITEM_ID
		WHERE REVIEW_ID = @REVIEW_ID
		AND TB_ITEM_TIMEPOINT.ITEM_ID = @ITEM_ID
		ORDER BY TIMEPOINT_VALUE

SET NOCOUNT OFF

GO

GO
/****** Object:  StoredProcedure [dbo].[st_ItemTimepointDelete]    Script Date: 07/03/2019 13:03:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[st_ItemTimepointDelete]
(
	@ITEM_TIMEPOINT_ID BIGINT
)

As

SET NOCOUNT ON

	DELETE FROM TB_ITEM_TIMEPOINT
		WHERE ITEM_TIMEPOINT_ID = @ITEM_TIMEPOINT_ID

SET NOCOUNT OFF


GO
/****** Object:  StoredProcedure [dbo].[st_ItemTimepointCreate]    Script Date: 09/03/2019 22:47:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].st_ItemTimepointCreate
(
	@ITEM_ID BIGINT
,	@TIMEPOINT_VALUE FLOAT
,	@TIMEPOINT_METRIC varchar(50)
,	@NEW_ITEM_TIMEPOINT_ID BIGINT OUTPUT
)

As

SET NOCOUNT ON



	INSERT INTO TB_ITEM_TIMEPOINT(ITEM_ID, TIMEPOINT_VALUE, TIMEPOINT_METRIC)
	VALUES(@ITEM_ID, @TIMEPOINT_VALUE, @TIMEPOINT_METRIC)
		
	SET @NEW_ITEM_TIMEPOINT_ID = @@IDENTITY

SET NOCOUNT OFF

