Use Reviewer
GO

IF COL_LENGTH('dbo.TB_REVIEW', 'OPEN_AI_ENABLED') IS NULL
BEGIN

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION

ALTER TABLE dbo.TB_REVIEW ADD
	OPEN_AI_ENABLED bit NULL

ALTER TABLE dbo.TB_REVIEW SET (LOCK_ESCALATION = TABLE)

COMMIT
END
GO