Use Reviewer
GO

IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'ENDPOINT') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		[ENDPOINT] nvarchar(500) not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_ENDPOINT 
		DEFAULT ('')
END
GO
IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'IS_PUBLIC') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		[IS_PUBLIC] bit not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_IS_PUBLIC
		DEFAULT (0)
END
GO
IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'TOP_P') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		TOP_P decimal(9,4) not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_TOP_P
		DEFAULT (0.95)
END
GO
IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'TEMPERATURE') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		TEMPERATURE decimal(9,4) not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_TEMPERATURE
		DEFAULT (0.0)
END
GO
IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'FREQUENCY_PENALTY') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		[FREQUENCY_PENALTY] decimal(9,4) not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_FREQUENCY_PENALTY
		DEFAULT (0.0)
END
GO
IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'PRESENCE_PENALTY') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		PRESENCE_PENALTY decimal(9,4) not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_PRESENCE_PENALTY
		DEFAULT (0.0)
END
GO

USE [Reviewer]
GO

/****** Object:  StoredProcedure [dbo].[st_RobotApiPastJobs]    Script Date: 13/05/2025 11:16:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER PROCEDURE [dbo].[st_RobotCoderList] 
(
	@isSiteAdmin bit = 0
)
AS
BEGIN
	
	if @isSiteAdmin = 0
	BEGIN
		SELECT * from TB_ROBOT_ACCOUNT rc
			inner join TB_CONTACT c on rc.CONTACT_ID = c.CONTACT_ID
		WHERE rc.IS_PUBLIC = 1
	END
	else
	BEGIN
		SELECT * from TB_ROBOT_ACCOUNT rc
			inner join TB_CONTACT c on rc.CONTACT_ID = c.CONTACT_ID
	END

END
GO

CREATE OR ALTER PROCEDURE [dbo].[st_RobotCoder] 
(
	@RobotName NVARCHAR(255)
)
AS
BEGIN
	SELECT * from TB_ROBOT_ACCOUNT rc
		inner join TB_CONTACT c on rc.CONTACT_ID = c.CONTACT_ID
	WHERE C.CONTACT_NAME = @RobotName
END
GO



