
Use Reviewer
GO

IF COL_LENGTH('dbo.TB_ROBOT_ACCOUNT', 'REQUESTS_PER_MINUTE') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ROBOT_ACCOUNT ADD
		REQUESTS_PER_MINUTE smallint not NULL
		CONSTRAINT D_TB_ROBOT_ACCOUNT_REQUESTS_PER_MINUTE 
		DEFAULT (150)
END
GO