Use Reviewer
GO

IF COL_LENGTH('dbo.TB_ROBOT_API_CALL_LOG', 'N_ITERATIONS') IS  NULL
BEGIN
 print 'adding NEW N_ITERATIONS col'
 Alter TABLE TB_ROBOT_API_CALL_LOG ADD N_ITERATIONS int NOT NULL DEFAULT(0);
END
GO

IF COL_LENGTH('dbo.TB_ROBOT_API_CALL_LOG', 'OPENAI_PROMPT_EVALUATION_ID') IS  NULL
BEGIN
 print 'adding NEW OPENAI_PROMPT_EVALUATION_ID col'
 Alter TABLE TB_ROBOT_API_CALL_LOG ADD OPENAI_PROMPT_EVALUATION_ID int NOT NULL DEFAULT(0);
END
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotApiCallLogCreate]    Script Date: 10/02/2026 22:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[st_RobotApiCallLogCreate] 
(
	@REVIEW_ID int,
	@CREDIT_PURCHASE_ID int,
	@ROBOT_NAME nvarchar(255),
	@CRITERIA varchar(max),
	@REVIEW_SET_ID int = 0,
	@CURRENT_ITEM_ID bigint,
	@FORCE_CODING_IN_ROBOT_NAME bit,
	@LOCK_CODING bit,
	@USE_PDFS bit,
	@CONTACT_ID int,
	@N_ITERATIONS int = 1,
	@OPENAI_PROMPT_EVALUATION_ID int = 0,
	@result varchar(50) OUTPUT, 
	@JobId int OUTPUT,
	@RobotContactId int OUTPUT
)
AS
BEGIN

	set @result = 'Success'
	declare @rID int = (select ROBOT_ID from TB_CONTACT c 
							Inner join TB_ROBOT_ACCOUNT rc on c.CONTACT_ID = rc.CONTACT_ID and c.CONTACT_NAME = @ROBOT_NAME
							AND c.EMAIL like '%FAKE@ucl.ac.uk' AND c.EXPIRY_DATE is null);
	IF @rID is null OR @rID < 1
	BEGIN
		set @result = 'Robot not found';
		return;
	END
	set @RobotContactId = (select CONTACT_ID from TB_ROBOT_ACCOUNT where ROBOT_ID = @rID)
	declare @chk int = (Select count(*) from  tb_review_set where REVIEW_SET_ID = @REVIEW_SET_ID and REVIEW_ID = @REVIEW_ID)
	if @chk < 1 and @REVIEW_SET_ID > 0
	BEGIN
		set @result = 'Coding tool not found';
		return;
	END
	set @chk = (select count(*) from TB_REVIEW_CONTACT where REVIEW_ID = @REVIEW_ID and CONTACT_ID = @RobotContactId)
	if @chk < 1
	BEGIN
		declare @CR int 
		insert into TB_REVIEW_CONTACT (REVIEW_ID, CONTACT_ID) values (@REVIEW_ID, @RobotContactId)
		SET @CR = SCOPE_IDENTITY()
		INSERT into TB_CONTACT_REVIEW_ROLE (REVIEW_CONTACT_ID, ROLE_NAME) values (@CR, 'Coding only')
	END

	insert into TB_ROBOT_API_CALL_LOG
		(CREDIT_PURCHASE_ID,REVIEW_ID,ROBOT_ID,REVIEW_SET_ID,CRITERIA,[STATUS], CURRENT_ITEM_ID 
		,SUCCESS,INPUT_TOKENS_COUNT,OUTPUT_TOKENS_COUNT,COST
		,FORCE_CODING_IN_ROBOT_NAME, LOCK_CODING, USE_PDFS, CONTACT_ID, N_ITERATIONS, OPENAI_PROMPT_EVALUATION_ID)
		VALUES
		(@CREDIT_PURCHASE_ID, @REVIEW_ID, @rID, @REVIEW_SET_ID, @CRITERIA, 'Starting', @CURRENT_ITEM_ID
		, 1, 0, 0, 0
		, @FORCE_CODING_IN_ROBOT_NAME, @LOCK_CODING, @USE_PDFS, @CONTACT_ID, @N_ITERATIONS, @OPENAI_PROMPT_EVALUATION_ID);
	SET @JobId = SCOPE_IDENTITY();
END
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotApiCreateQueuedJob]    Script Date: 15/02/2026 22:37:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[st_RobotApiCreateQueuedJob] 
(
	@REVIEW_ID int,
	@ROBOT_NAME nvarchar(255),
	@CRITERIA varchar(max),
	@CREDIT_PURCHASE_ID int,
	@REVIEW_SET_ID int,
	@FORCE_CODING_IN_ROBOT_NAME bit,
	@LOCK_CODING bit,
	@USE_PDFS bit,
	@CONTACT_ID int,
	@N_ITERATIONS int = 1,
	@OPENAI_PROMPT_EVALUATION_ID int = 0,
	@RESULT varchar(100) output,
	@ROBOT_API_CALL_ID int output
)
AS
BEGIN
	declare @rID int = (select ROBOT_ID from TB_CONTACT c 
							Inner join TB_ROBOT_ACCOUNT rc on c.CONTACT_ID = rc.CONTACT_ID and c.CONTACT_NAME = @ROBOT_NAME
							AND c.EMAIL like '%FAKE@ucl.ac.uk' AND c.EXPIRY_DATE is null);
	IF @rID is null OR @rID < 1
	BEGIN
		set @result = 'Robot not found';
		return;
	END
	declare @RobotContactId int = (select CONTACT_ID from TB_ROBOT_ACCOUNT where ROBOT_ID = @rID)

	declare @chk int = (select count(*) from TB_REVIEW_CONTACT where REVIEW_ID = @REVIEW_ID and CONTACT_ID = @RobotContactId)
	if @chk < 1
	BEGIN
		declare @CR int 
		insert into TB_REVIEW_CONTACT (REVIEW_ID, CONTACT_ID) values (@REVIEW_ID, @RobotContactId)
		SET @CR = SCOPE_IDENTITY()
		INSERT into TB_CONTACT_REVIEW_ROLE (REVIEW_CONTACT_ID, ROLE_NAME) values (@CR, 'Coding only')
	END

	INSERT into TB_ROBOT_API_CALL_LOG (CREDIT_PURCHASE_ID, REVIEW_ID, ROBOT_ID, REVIEW_SET_ID
			, CRITERIA, [STATUS], CURRENT_ITEM_ID, [DATE_CREATED] ,[DATE_UPDATED] ,[SUCCESS],[INPUT_TOKENS_COUNT]
			,[OUTPUT_TOKENS_COUNT] ,[COST] ,[FORCE_CODING_IN_ROBOT_NAME] ,[LOCK_CODING] , USE_PDFS, CONTACT_ID
			,N_ITERATIONS, OPENAI_PROMPT_EVALUATION_ID)
		values
		(
			@CREDIT_PURCHASE_ID, @REVIEW_ID, @rID, @REVIEW_SET_ID
			, @CRITERIA, 'Queued', 0, GETDATE(), GETDATE(), 1, 0
			, 0, 0, @FORCE_CODING_IN_ROBOT_NAME, @LOCK_CODING, @USE_PDFS, @CONTACT_ID
			, @N_ITERATIONS, @OPENAI_PROMPT_EVALUATION_ID
		);
	set @ROBOT_API_CALL_ID = SCOPE_IDENTITY();
	set @RESULT = 'Success';
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
           WHERE TABLE_NAME = N'TB_OPENAI_PROMPT_EVALUATION')
BEGIN
 print 'adding NEW TB_OPENAI_PROMPT_EVALUATION table'

	CREATE TABLE TB_OPENAI_PROMPT_EVALUATION
	(
		OPENAI_PROMPT_EVALUATION_ID [int] IDENTITY(1,1) NOT NULL
		, REVIEW_ID INT FOREIGN KEY REFERENCES TB_REVIEW(REVIEW_ID)
		, TITLE NVARCHAR(4000)
		, REVIEW_SET_HTML NVARCHAR(MAX)
		, GOLD_STANDARD_ATTRIBUTE_ID BIGINT
		, N_RECORDS INT
		, N_ITERATIONS INT
		, REVIEW_SET_ID INT
		, GOLD_STANDARD_ATTRIBUTE_NAME NVARCHAR(255)
		, N_CODES INT
		, ROBOT_NAME NVARCHAR(255)
		, WHEN_RUN DATETIME
		, USE_PDFS bit NOT NULL
		, CONTACT_ID INT FOREIGN KEY REFERENCES TB_CONTACT(CONTACT_ID)
		, CONTACT_NAME NVARCHAR(255)
		, TP INT NULL
		, FP INT NULL
		, TN INT NULL
		, FN INT NULL
		CONSTRAINT PK_OPENAI_PROMPT_EVALUATION_ID PRIMARY KEY(OPENAI_PROMPT_EVALUATION_ID)
	)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
           WHERE TABLE_NAME = N'TB_OPENAI_PROMPT_EVALUATION_DATA')
BEGIN
	CREATE TABLE TB_OPENAI_PROMPT_EVALUATION_DATA
	(
		OPENAI_PROMPT_EVALUATION_DATA_ID [int] IDENTITY(1,1) NOT NULL
		, OPENAI_PROMPT_EVALUATION_ID INT FOREIGN KEY REFERENCES TB_OPENAI_PROMPT_EVALUATION(OPENAI_PROMPT_EVALUATION_ID)
		, ITEM_ID BIGINT
		, ITERATION INT
		, ATTRIBUTE_ID BIGINT
		, ATTRIBUTE_NAME NVARCHAR(255)
		, ADDITIONAL_TEXT NVARCHAR(MAX) NULL
		, GOLD_STANDARD BIT
		CONSTRAINT PK_OPENAI_PROMPT_EVALUATION_DATA_ID PRIMARY KEY(OPENAI_PROMPT_EVALUATION_DATA_ID)
	)
END
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_UpdateOpenAiPromptEvaluation]    Script Date: 13/02/2026 14:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_UpdateOpenAiPromptEvaluation]
(

	@OPENAI_PROMPT_EVALUATION_ID INT
,	@STATUS varchar(10)
)
As

SET NOCOUNT ON
	
DECLARE @TP DECIMAL(6,5), @TN DECIMAL(6,5), @FP DECIMAL(6,5), @FN DECIMAL(6,5)

IF @STATUS = 'Failed'
BEGIN
	UPDATE TB_OPENAI_PROMPT_EVALUATION
		SET TITLE = CONCAT(TITLE, ' (FAILED)'),
		TP = 0, FP = 0, TN = 0, FN = 0
	WHERE OPENAI_PROMPT_EVALUATION_ID = @OPENAI_PROMPT_EVALUATION_ID
END
ELSE
BEGIN

WITH GOLD_STANDARDStandard AS (  
    -- Get the GOLD_STANDARD standard ATTRIBUTE_IDs for each ITEM_ID  
    SELECT ITEM_ID, ATTRIBUTE_ID  
    FROM TB_OPENAI_PROMPT_EVALUATION_DATA  
    WHERE GOLD_STANDARD = 1  and openai_prompt_evaluation_id = @OPENAI_PROMPT_EVALUATION_ID
),  
LLMPredictions AS (  
    -- Get LLM predictions for each ITEM_ID and iteration  
    SELECT ITEM_ID, ATTRIBUTE_ID, ITERATION  
    FROM TB_OPENAI_PROMPT_EVALUATION_DATA  
    WHERE GOLD_STANDARD = 0 and openai_prompt_evaluation_id = @OPENAI_PROMPT_EVALUATION_ID
),  
AllATTRIBUTE_IDs AS (  
    -- Get all unique ATTRIBUTE_IDs in the dataset  
    SELECT DISTINCT ATTRIBUTE_ID  
		FROM TB_OPENAI_PROMPT_EVALUATION_DATA where openai_prompt_evaluation_id = @OPENAI_PROMPT_EVALUATION_ID
	),  
	AllCombinations AS (  
		-- Create all combinations of ITEM_ID, ATTRIBUTE_ID, and ITERATION  
		SELECT DISTINCT l.ITEM_ID, a.ATTRIBUTE_ID, l.ITERATION  
		FROM LLMPredictions l  
		CROSS JOIN AllATTRIBUTE_IDs a  
	),  
	ConfusionMatrix AS (  
		SELECT   
			ac.ITERATION,  
			ac.ATTRIBUTE_ID,  
			ac.ITEM_ID,  
			-- True Positive: Both GOLD_STANDARD and LLM have the ATTRIBUTE_ID  
			CASE WHEN g.ITEM_ID IS NOT NULL AND l.ITEM_ID IS NOT NULL THEN 1 ELSE 0 END AS TP,  
			-- True Negative: Neither GOLD_STANDARD nor LLM have the ATTRIBUTE_ID  
			CASE WHEN g.ITEM_ID IS NULL AND l.ITEM_ID IS NULL THEN 1 ELSE 0 END AS TN,  
			-- False Positive: LLM has it, GOLD_STANDARD doesn't  
			CASE WHEN g.ITEM_ID IS NULL AND l.ITEM_ID IS NOT NULL THEN 1 ELSE 0 END AS FP,  
			-- False Negative: GOLD_STANDARD has it, LLM doesn't  
			CASE WHEN g.ITEM_ID IS NOT NULL AND l.ITEM_ID IS NULL THEN 1 ELSE 0 END AS FN  
		FROM AllCombinations ac  
		LEFT JOIN GOLD_STANDARDStandard g   
			ON ac.ITEM_ID = g.ITEM_ID AND ac.ATTRIBUTE_ID = g.ATTRIBUTE_ID  
		LEFT JOIN LLMPredictions l   
			ON ac.ITEM_ID = l.ITEM_ID AND ac.ATTRIBUTE_ID = l.ATTRIBUTE_ID AND ac.ITERATION = l.ITERATION  
	),  
	IterationStats AS (  
		-- Sum up confusion matrix values per iteration  
		SELECT   
			ITERATION,  
			SUM(TP) AS Total_TP,  
			SUM(TN) AS Total_TN,  
			SUM(FP) AS Total_FP,  
			SUM(FN) AS Total_FN  
		FROM ConfusionMatrix  
		GROUP BY ITERATION  
	)
	-- Calculate averages across all iterations  
	SELECT   
		@TP = AVG(CAST(Total_TP AS FLOAT)),  
		@TN = AVG(CAST(Total_TN AS FLOAT)),  
		@FP = AVG(CAST(Total_FP AS FLOAT)),  
		@FN = AVG(CAST(Total_FN AS FLOAT))  
	FROM IterationStats;  

	UPDATE TB_OPENAI_PROMPT_EVALUATION
		SET TP = @TP,
			FP = @FP,
			TN = @TN,
			FN = @FN
		WHERE OPENAI_PROMPT_EVALUATION_ID = @OPENAI_PROMPT_EVALUATION_ID
END

SET NOCOUNT OFF
GO


CREATE OR ALTER Procedure [dbo].[st_ItemIDPerAttributeID](
	@AttributeId bigint NULL
,	@ReviewId int NULL
,	@Result nvarchar(max) OUTPUT
)
as
Begin

SELECT @result =
    STRING_AGG(CAST(item_id AS varchar(20)), ',')
FROM (
    SELECT DISTINCT ir.ITEM_ID from
    TB_ITEM_REVIEW ir
	  inner join TB_ITEM_ATTRIBUTE tia on ir.REVIEW_ID = @ReviewId and tia.ATTRIBUTE_ID = @AttributeId and ir.ITEM_ID = tia.ITEM_ID and ir.IS_DELETED = 0
	  inner join tb_item_set tis on tia.ITEM_SET_ID = tis.ITEM_SET_ID and tis.IS_COMPLETED = 1
) AS d;
End
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotOpenAIPromptEvaluationCreate]    Script Date: 15/02/2026 23:35:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   procedure [dbo].[st_RobotOpenAIPromptEvaluationCreate]
(
	@REVIEW_ID INT
,	@TITLE nvarchar(4000)
,	@ROBOT_NAME NVARCHAR(255)
,	@REVIEW_SET_ID INT
,	@GOLD_STANDARD_ATTRIBUTE_ID bigint
,	@GOLD_STANDARD_ATTRIBUTE_NAME NVARCHAR(255)
,	@N_RECORDS INT
,	@N_CODES INT
,	@REVIEW_SET_HTML nvarchar(max)
,	@USE_PDFS bit
,	@N_ITERATIONS INT
,	@CONTACT_ID INT
,	@CONTACT_NAME NVARCHAR(255)
,	@NEW_OPENAI_PROMPT_EVALUATION_ID INT OUTPUT
)

As

SET NOCOUNT ON

	INSERT INTO TB_OPENAI_PROMPT_EVALUATION(REVIEW_ID, TITLE, REVIEW_SET_HTML, GOLD_STANDARD_ATTRIBUTE_ID, GOLD_STANDARD_ATTRIBUTE_NAME, N_RECORDS, N_ITERATIONS, REVIEW_SET_ID,
		N_CODES, ROBOT_NAME, CONTACT_ID, CONTACT_NAME, WHEN_RUN, USE_PDFS)
	VALUES(@REVIEW_ID, @TITLE, @REVIEW_SET_HTML, @GOLD_STANDARD_ATTRIBUTE_ID, @GOLD_STANDARD_ATTRIBUTE_NAME, @N_RECORDS, @N_ITERATIONS, @REVIEW_SET_ID,
		@N_CODES, @ROBOT_NAME, @CONTACT_ID, @CONTACT_NAME, GETDATE(), @USE_PDFS)

	SET @NEW_OPENAI_PROMPT_EVALUATION_ID = @@IDENTITY

	INSERT INTO TB_OPENAI_PROMPT_EVALUATION_DATA(OPENAI_PROMPT_EVALUATION_ID, ITEM_ID, ITERATION, ATTRIBUTE_ID, ATTRIBUTE_NAME, ADDITIONAL_TEXT, GOLD_STANDARD)
	select distinct @NEW_OPENAI_PROMPT_EVALUATION_ID, ia.ITEM_ID, 0, ia.ATTRIBUTE_ID, a.ATTRIBUTE_NAME, ia.ADDITIONAL_TEXT, 1 from tb_review_set rs
		  inner join tb_item_set iset on iset.SET_ID = rs.SET_ID and iset.IS_COMPLETED = 1
		  inner join TB_ITEM_ATTRIBUTE ia on ia.ITEM_SET_ID = iset.ITEM_SET_ID
		  inner join TB_ITEM_REVIEW ir on ir.REVIEW_ID = rs.REVIEW_ID
		  inner join TB_ATTRIBUTE a on a.ATTRIBUTE_ID = ia.ATTRIBUTE_ID
		  where REVIEW_SET_Id = @REVIEW_SET_ID and ir.IS_DELETED = 0 and ia.ITEM_ID in
		  (
			SELECT IA2.ITEM_ID FROM TB_ITEM_ATTRIBUTE IA2
			INNER JOIN TB_ITEM_SET ISET2 ON ISET2.ITEM_SET_ID = IA2.ITEM_SET_ID AND ISET2.IS_COMPLETED = 1
			WHERE IA2.ATTRIBUTE_ID = @GOLD_STANDARD_ATTRIBUTE_ID
		  )

	
SET NOCOUNT OFF
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotOpenAIPromptEvaluationDelete]    Script Date: 13/02/2026 14:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_RobotOpenAIPromptEvaluationDelete]
(
	@OPENAI_PROMPT_EVALUATION_ID INT
)

As

SET NOCOUNT ON

	DELETE FROM TB_OPENAI_PROMPT_EVALUATION_DATA
		WHERE OPENAI_PROMPT_EVALUATION_ID = @OPENAI_PROMPT_EVALUATION_ID

	DELETE FROM TB_OPENAI_PROMPT_EVALUATION
		WHERE OPENAI_PROMPT_EVALUATION_ID = @OPENAI_PROMPT_EVALUATION_ID

	
SET NOCOUNT OFF
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotOpenAIPromptEvaluationList]    Script Date: 13/02/2026 14:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_RobotOpenAIPromptEvaluationList]
(
	@ReviewId INT
)

As

SET NOCOUNT ON

	Select * FROM TB_OPENAI_PROMPT_EVALUATION
		WHERE REVIEW_ID = @ReviewId
	
SET NOCOUNT OFF
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotOpenAIPromptEvaluation]    Script Date: 13/02/2026 14:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_RobotOpenAIPromptEvaluation]
(
	@OPENAI_PROMPT_EVALUATION_ID INT
)

As

SET NOCOUNT ON

	Select * FROM TB_OPENAI_PROMPT_EVALUATION
		WHERE OPENAI_PROMPT_EVALUATION_ID = @OPENAI_PROMPT_EVALUATION_ID
	
SET NOCOUNT OFF
GO

------------------------------------------------------------

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotOpenAIPromptEvaluationDataList]    Script Date: 13/02/2026 14:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_RobotOpenAIPromptEvaluationDataList]
(
	@OPENAI_PROMPT_EVALUATION_ID INT
)

As

SET NOCOUNT ON

	Select * FROM TB_OPENAI_PROMPT_EVALUATION_DATA
		WHERE OPENAI_PROMPT_EVALUATION_ID = @OPENAI_PROMPT_EVALUATION_ID
	
SET NOCOUNT OFF
GO