USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_RobotOpenAIPromptEvaluationDataInsert]    Script Date: 17/02/2026 12:48:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER   procedure [dbo].[st_RobotOpenAIPromptEvaluationDataInsert]
(

	@OPENAI_PROMPT_EVALUATION_ID INT
,	@ITEM_ID BIGINT
,	@ITERATION INT
,	@ATTRIBUTE_ID BIGINT
,	@ADDITIONAL_TEXT NVARCHAR(MAX)
,	@GOLD_STANDARD BIT
)
As

SET NOCOUNT ON

	declare @AttributeName nvarchar(255)
	select @AttributeName = ATTRIBUTE_NAME from TB_ATTRIBUTE where ATTRIBUTE_ID = @ATTRIBUTE_ID

	INSERT INTO TB_OPENAI_PROMPT_EVALUATION_DATA(OPENAI_PROMPT_EVALUATION_ID, ITEM_ID, ITERATION, ATTRIBUTE_ID, ATTRIBUTE_NAME, ADDITIONAL_TEXT, GOLD_STANDARD)
	VALUES(@OPENAI_PROMPT_EVALUATION_ID, @ITEM_ID, @ITERATION, @ATTRIBUTE_ID, @AttributeName, @ADDITIONAL_TEXT, @GOLD_STANDARD)
SET NOCOUNT OFF
GO