USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ComparisonAttributesList]    Script Date: 14/06/2019 11:59:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[st_ComparisonAttributesList]
(
	@COMPARISON_ID INT,
	@PARENT_ATTRIBUTE_ID BIGINT = 0,
	@SET_ID INT
)

As

SET NOCOUNT ON

	SELECT COMPARISON_ITEM_ATTRIBUTE_ID, COMPARISON_ID, tb_COMPARISON_ITEM_ATTRIBUTE.ITEM_ID, tb_COMPARISON_ITEM_ATTRIBUTE.ATTRIBUTE_ID,
		ADDITIONAL_TEXT, tb_COMPARISON_ITEM_ATTRIBUTE.CONTACT_ID, tb_COMPARISON_ITEM_ATTRIBUTE.SET_ID,
		ATTRIBUTE_NAME, TITLE, CAST('FALSE' AS BIT) IS_COMPLETED
		, CASE when ARM_NAME is null then '' ELSE ARM_NAME end AS ARM_NAME
	FROM tb_COMPARISON_ITEM_ATTRIBUTE
		INNER JOIN TB_ATTRIBUTE ON TB_ATTRIBUTE.ATTRIBUTE_ID = tb_COMPARISON_ITEM_ATTRIBUTE.ATTRIBUTE_ID
		INNER JOIN TB_ITEM ON TB_ITEM.ITEM_ID = tb_COMPARISON_ITEM_ATTRIBUTE.ITEM_ID
		INNER JOIN TB_ATTRIBUTE_SET ON TB_ATTRIBUTE_SET.ATTRIBUTE_ID = tb_COMPARISON_ITEM_ATTRIBUTE.ATTRIBUTE_ID
			AND TB_ATTRIBUTE_SET.PARENT_ATTRIBUTE_ID = @PARENT_ATTRIBUTE_ID
			AND TB_ATTRIBUTE_SET.SET_ID = @SET_ID
		LEFT OUTER JOIN TB_ITEM_ARM on tb_COMPARISON_ITEM_ATTRIBUTE.ITEM_ARM_ID = TB_ITEM_ARM.ITEM_ARM_ID
	WHERE COMPARISON_ID = @COMPARISON_ID
	
	UNION
	
	SELECT 0, @COMPARISON_ID, TB_ITEM_ATTRIBUTE.ITEM_ID, TB_ITEM_ATTRIBUTE.ATTRIBUTE_ID, TB_ITEM_ATTRIBUTE.ADDITIONAL_TEXT, 
		TB_ITEM_SET.CONTACT_ID, TB_ITEM_SET.SET_ID, ATTRIBUTE_NAME, TITLE, CAST('TRUE' AS BIT) IS_COMPLETED
		, CASE when ARM_NAME is null then '' ELSE ARM_NAME end AS ARM_NAME
	FROM TB_ITEM_ATTRIBUTE
		INNER JOIN TB_ITEM_SET ON TB_ITEM_SET.ITEM_SET_ID = TB_ITEM_ATTRIBUTE.ITEM_SET_ID
			AND TB_ITEM_SET.SET_ID = @SET_ID
		INNER JOIN TB_ATTRIBUTE ON TB_ATTRIBUTE.ATTRIBUTE_ID = TB_ITEM_ATTRIBUTE.ATTRIBUTE_ID
		INNER JOIN TB_ITEM ON TB_ITEM.ITEM_ID = TB_ITEM_ATTRIBUTE.ITEM_ID
		INNER JOIN tb_COMPARISON_ITEM_ATTRIBUTE ON tb_COMPARISON_ITEM_ATTRIBUTE.ITEM_ID = TB_ITEM_ATTRIBUTE.ITEM_ID
			AND tb_COMPARISON_ITEM_ATTRIBUTE.COMPARISON_ID = @COMPARISON_ID
		INNER JOIN TB_ATTRIBUTE_SET ON TB_ATTRIBUTE_SET.ATTRIBUTE_ID = tb_COMPARISON_ITEM_ATTRIBUTE.ATTRIBUTE_ID
			AND TB_ATTRIBUTE_SET.PARENT_ATTRIBUTE_ID = @PARENT_ATTRIBUTE_ID
			AND TB_ATTRIBUTE_SET.SET_ID = @SET_ID
		LEFT OUTER JOIN TB_ITEM_ARM on TB_ITEM_ATTRIBUTE.ITEM_ARM_ID = TB_ITEM_ARM.ITEM_ARM_ID
	WHERE TB_ITEM_SET.IS_COMPLETED = 'TRUE'
	
	ORDER BY ITEM_ID, CONTACT_ID
	
SET NOCOUNT OFF
GO