declare @AttributeId0 bigint
declare @AttributeId1 bigint
declare @AttributeId2 bigint
declare @AttributeId3 bigint
declare @AttributeId4 bigint
declare @AttributeId5 bigint
declare @AttributeId6 bigint
declare @AttributeId7 bigint
declare @AttributeId8 bigint
declare @AttributeId9 bigint
declare @SET_ID INT

INSERT INTO TB_SET(SET_TYPE_ID, SET_NAME, OLD_GUIDELINE_ID, SET_DESCRIPTION, ORIGINAL_SET_ID, USER_CAN_EDIT_URLS)
VALUES(3, 'New Prioritised Codeset','111925', 'Codeset to annotate the prioritised entities for the complete ontology ', 111925, 1)
SET @SET_ID = @@IDENTITY
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Population', 6080465)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate age', 6080480)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mean age', 6080481)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','All male', 6080483)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','All female', 6080484)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion identifying as female gender', 6080485)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion identifying as male gender', 6080486)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion identifying as other gender', 6080487)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion identifying as belonging to a specific ethnic group', 6080488)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate language proficiency', 6080489)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate socioeconomic factors', 6080490)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 10)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate income and material resources', 6080491)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 11)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion belonging to specified individual income category', 6450783)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 12)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion belonging to specified family or household income category', 6080492)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 13)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion having a specific type of health insurance coverage', 6080493)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 14)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate number of years in education completed', 6080494)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 15)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mean number of years in education completed', 6080495)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate highest level of formal educational qualification achieved', 6080496)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 16)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion achieved primary education', 6080497)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion achieved secondary education', 6080498)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion achieved university or college education', 6080499)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate employment status', 6080500)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 17)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion employed', 6080501)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion unemployed', 6080502)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate socioeconomic status', 6080503)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 18)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate interpersonal roles', 6080504)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 19)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate relationship status', 6080505)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Proportion in a legal marriage or union', 6080506)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate organisational role', 6080507)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 20)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate patient role', 6080508)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate student or trainee role', 6080509)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate job type', 6496183)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate health status type', 6080510)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 21)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Aggregate behavior', 6080511)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 22)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mean number of times tobacco used', 6080512)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mean age of tobacco use initation', 6080513)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Cigarette dependence', 6494127)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 23)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Setting', 6080466)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Geographical location', 6080516)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Country of intervention', 6080517)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Lower-level geographical region', 6080518)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Attribute of location', 6080519)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Area social and economic condition', 6080523)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Low-income area', 6080524)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','High-income area', 6080573)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Population and resource density', 6080574)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Rural area', 6080616)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Suburban area', 6080623)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Urban area', 6080624)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Site', 6080520)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Facility', 6080521)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Residential facility', 6080626)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Healthcare facility', 6080628)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Doctor-led primary care facility', 6080630)
SET @AttributeId4 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId4, @SET_ID, @AttributeId3, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Hospital facility', 6080629)
SET @AttributeId4 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId4, @SET_ID, @AttributeId3, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Rehabilitation facility', 6080631)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Psychiatric facility', 6080632)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Educational facility', 6080633)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Community facility', 6080634)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Research facility', 6080635)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Outdoor environment', 6080522)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Intervention', 6452741)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','BCTs', 6452742)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1. Goals and planning', 6452743)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.1.Goal setting (behavior)', 6452744)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.2 Problem solving ', 6452745)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.3 Goal setting (outcome)', 6452746)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.4 Action planning', 6452747)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.5 Review behavior goal(s)', 6452748)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.6 Discrepancy between current behavior and goal', 6452749)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.7 Review outcome goal(s)', 6452750)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.8 Behavioral contract', 6452751)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','1.9 Commitment', 6452752)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2. Feedback and monitoring', 6452753)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.1 Monitoring of behavior by others without feedback', 6452754)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.2 Feedback on behaviour', 6452755)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.3 Self-monitoring of behavior', 6452756)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.4 Self-monitoring of outcome(s) of behaviour', 6452757)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.5 Monitoring of outcome(s) of behavior without feedback', 6452758)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.6 Biofeedback', 6452759)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','2.7 Feedback on outcome(s) of behavior', 6452760)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','3. Social support', 6452761)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','3.1 Social support (unspecified)', 6452762)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','3.2 Social support (practical) ', 6452763)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','3.3 Social support (emotional) ', 6452764)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','4. Shaping Knowledge', 6452765)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','4.1 Instruction on how to perform the behavior', 6452830)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','4.2 Information about Antecedents', 6452831)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','4.3 Re-attribution', 6452832)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','4.4 Behavioral experiments', 6452833)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','4.5. Advise to change behavior', 6452834)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5. Natural consequences', 6452836)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5.1 Information about health consequences', 6452837)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5.2 Salience of consequences', 6452838)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5.3 Information about social and environmental consequences', 6452839)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5.4 Monitoring of emotional consequences', 6452840)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5.5 Anticipated regret', 6452843)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','5.6 Information about emotional consequences', 6452844)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','6. Comparison of behavior', 6452845)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','6.1 Demonstration of behavior', 6452846)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','6.2 Social comparison', 6452847)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','6.3 Information about others approval', 6452848)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7. Associations', 6452849)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.1 Prompts/cues', 6452850)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.2 Cue signalling reward', 6452851)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.3 Reduce prompts/cues', 6452852)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.4 Remove access to the reward', 6452853)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.5 Remove aversive stimulus', 6452854)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.6 Satiation', 6452855)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.7 Exposure', 6452856)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','7.8 Associative learning ', 6452857)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8. Repetition and substitution', 6452858)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.1 Behavioral practice/rehearsal', 6452859)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.2 Behavior substitution ', 6452860)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.3 Habit formation ', 6452861)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.4 Habit reversal ', 6452862)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.5 Overcorrection ', 6452863)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.6 Generalisation of target behavior', 6452864)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','8.7 Graded tasks', 6452865)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','9. Comparison of outcomes', 6452930)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','9.1 Credible source', 6452931)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','9.2 Pros and cons', 6452932)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','9.3 Comparative imagining of future outcomes', 6452933)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10. Reward and threat', 6452934)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 10)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.1 Material incentive (behavior)', 6452935)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.2 Material reward (behavior) ', 6452936)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.3 Non-specific reward ', 6452937)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.4 Social reward ', 6452938)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.5 Social incentive ', 6452939)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.6 Non-specific incentive ', 6452940)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.7 Self-incentive ', 6452941)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.8 Incentive (outcome) ', 6452942)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.9 Self-reward ', 6452943)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.10 Reward (outcome)', 6452944)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 10)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','10.11 Future punishment', 6452945)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 11)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','11. Regulation', 6452946)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 11)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','11.1 Pharmacological support ', 6452947)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','11.2 Reduce negative emotions ', 6452948)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','11.3 Conserving mental resources ', 6452949)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','11.4 Paradoxical instructions', 6452950)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12. Antecedents', 6452952)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 12)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12.1 Restructuring the physical environment', 6452953)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12.2 Restructuring the social environment', 6452954)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12.3 Avoidance/reducing exposure to cues for the behavior', 6452955)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12.4 Distraction', 6452956)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12.5 Adding objects to the environment', 6452957)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','12.6 Body changes', 6452959)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','13. Identity', 6452960)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 13)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','13.1 Identification of self as role model', 6452961)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','13.2 Framing/reframing ', 6452962)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','13.3 Incompatible beliefs ', 6452963)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','13.4 Valued self-identify ', 6452964)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','13.5 Identity associated with changed behavior', 6452965)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14. Scheduled consequences', 6452966)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 14)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.1 Behavior cost', 6452967)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.2 Punishment ', 6452968)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.3 Remove reward ', 6452969)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.4 Reward approximation', 6452970)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.5 Rewarding completion ', 6452973)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.6 Situation-specific reward ', 6452974)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.7 Reward incompatible behavior ', 6452975)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.8 Reward alternative behavior ', 6452976)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.9 Reduce reward frequency ', 6452977)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','14.10 Remove punishment', 6452978)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 10)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','15. Self-belief', 6452979)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 15)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','15.1 Verbal persuasion about capability', 6452980)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','15.2 Mental rehearsal of successful performance', 6452981)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','15.3 Focus on past success ', 6452982)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','15.4 Self-talk', 6452983)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','16. Covert learning', 6452984)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 16)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','16.1 Imaginary punishment ', 6452985)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','16.2 Imaginary reward ', 6452986)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','16.3 Vicarious consequences', 6452987)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Outcome (behaviour)', 6080469)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Behaviour type', 6451286)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Tobacco use', 6451287)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Smoking', 6451288)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Other tobacco use', 6451758)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Alcohol use', 6451759)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Physical activity', 6451760)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Eating', 6451761)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Modification type', 6451762)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Onset', 6451763)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Increase', 6451764)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Decrease', 6451765)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Abstinence', 6469471)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Quit attempt', 6451766)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Maintenance', 6451767)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Follow up', 6451768)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','One off assessment', 6451771)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Time point', 6451772)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Repeated assessment', 6451773)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','First follow up', 6451774)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Second follow up', 6451775)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Third follow up', 6451776)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Fourth follow up', 6451777)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Fifth follow up', 6451778)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Sixth follow up', 6451779)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Seventh follow up', 6451780)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Longest follow up', 6451781)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Behaviour assessment', 6451782)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Subjective assessment', 6451783)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Self report', 6451784)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Informant verified', 6451785)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Objective assessment', 6451786)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Biochemical verification', 6451787)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Observation', 6451788)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Activity monitor', 6451789)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Outcome (behaviour) value', 6080470)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Outcome value', 6451790)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Unit of measurement', 6451791)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect', 6080471)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect Size', 6452261)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect size type', 6452262)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Odds Ratio', 6452263)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Rate Ratio', 6452264)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Risk Ratio', 6452265)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Risk Difference', 6452266)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mean Difference', 6452267)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Median Difference', 6452268)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Hazard Ratio', 6452269)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Relative Risk', 6452270)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Chi square', 6452271)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect size estimate', 6452272)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect size p value', 6452273)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Significant (Text only)', 6452274)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Non significant (Text only)', 6452275)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect size lower 95% CI', 6452276)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Effect size upper 95% CI', 6452277)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Modes of Delivery', 6080474)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Face to face', 6080686)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Distance', 6080687)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Printed material', 6080688)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Digital', 6080689)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Technology for delivery', 6099187)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mobile device', 6080690)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Wearable accessory', 6099188)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Digital content type', 6080691)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Website / Computer Program / App', 6080692)
SET @AttributeId3 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId3, @SET_ID, @AttributeId2, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Somatic', 6080693)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Patch', 6080694)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Pill', 6080695)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Wearable', 6080696)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Cross-cutting attributes', 6080697)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Individual', 6080698)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Dyadic/Couples', 6080699)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Group-based', 6080701)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Format', 6080702)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Source', 6080475)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 8)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Role of Source', 6080703)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Health Professional', 6080704)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Teaching Professional', 6080705)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Psychologist', 6080706)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Sport and Fitness Worker', 6080707)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Researcher not otherwise specified', 6080708)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Student or trainee', 6080709)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 6)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Interventionist not otherwise specified', 6080710)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 7)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Socio-demographics of Source', 6080711)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Relatedness between source and intervention recipients', 6080712)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Family member', 6080713)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Expertise of Source', 6080714)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Reach', 6080476)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 9)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Allocated', 6080715)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Individual-level allocated', 6080717)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Cluster-level allocated', 6080718)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Analysed', 6080716)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Individual-level analysed', 6080719)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Cluster-level analysed', 6080720)
SET @AttributeId2 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId2, @SET_ID, @AttributeId1, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Individual reasons for attrition', 6823477)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Schedule', 6080477)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 10)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Overall duration', 6080721)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Number of contacts', 6080722)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Contact frequency', 6080723)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Contact duration', 6080724)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Dose', 6099675)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 11)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Engagement', 6823478)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 12)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Encountered intervention', 6823479)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Completed intervention', 6823480)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Fidelity', 6823481)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 13)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Sessions delivered', 6823482)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Labelled interventions', 6823483)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 14)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Cognitive Behavioural Therapy', 6823484)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Mindfulness', 6823485)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Motivational interviewing', 6823486)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Brief advice', 6823487)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Physical activity', 6823488)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 5)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Funding', 6830263)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 15)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Pharmaceutical company funding', 6830264)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Tobacco company funding', 6830265)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Research grant funding', 6830266)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','No funding', 6830276)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Competing interests', 6830267)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 16)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Pharmaceutical company competing interest', 6830268)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Tobacco company competing interest', 6830269)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Research grant competing interest', 6830270)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','No competing interest', 6830271)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Supplementary information', 6080479)
SET @AttributeId0 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId0, @SET_ID, 0, 2, 17)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Linked publications', 6090647)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 1)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Supplementary materials', 6090648)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 2)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','External materials', 6090649)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 3)
INSERT INTO TB_ATTRIBUTE(Ext_URL, Ext_Type, ATTRIBUTE_NAME, ORIGINAL_ATTRIBUTE_ID)
VALUES('','','Available from authors', 6090650)
SET @AttributeId1 = @@IDENTITY
INSERT INTO TB_ATTRIBUTE_SET(ATTRIBUTE_ID, SET_ID, PARENT_ATTRIBUTE_ID, ATTRIBUTE_TYPE_ID, ATTRIBUTE_ORDER)
VALUES(@AttributeId1, @SET_ID, @AttributeId0, 2, 4)