USE [REVIEWER]
GO
ALTER TABLE tb_set
ALTER COLUMN set_description NVARCHAR(MAX) NULL;
GO

USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ReviewSetInsert]    Script Date: 03/04/2026 12:27:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   procedure [dbo].[st_ReviewSetInsert]
(
	@REVIEW_ID INT,
	@SET_TYPE_ID INT = 3,
	@ALLOW_CODING_EDITS BIT = false,
	@SET_NAME NVARCHAR(255),
	@CODING_IS_FINAL BIT = true,
	@SET_ORDER INT = 0,
	@SET_DESCRIPTION nvarchar(max) = '',
	@ORIGINAL_SET_ID int = null,
	@OLDEST_KNOWN_SET_ID int = null,
	@NEW_REVIEW_SET_ID INT OUTPUT,
	@NEW_SET_ID INT OUTPUT
)

As

SET NOCOUNT ON

	INSERT INTO TB_SET(SET_TYPE_ID, SET_NAME, SET_DESCRIPTION, ORIGINAL_SET_ID, OLDEST_KNOWN_SET_ID, USER_CAN_EDIT_URLS)
		VALUES(@SET_TYPE_ID, @SET_NAME, @SET_DESCRIPTION, @ORIGINAL_SET_ID, @OLDEST_KNOWN_SET_ID, 'False')

	SET @NEW_SET_ID = @@IDENTITY

	INSERT INTO TB_REVIEW_SET(REVIEW_ID, SET_ID, ALLOW_CODING_EDITS, CODING_IS_FINAL, SET_ORDER)
		VALUES(@REVIEW_ID, @NEW_SET_ID, @ALLOW_CODING_EDITS, @CODING_IS_FINAL, @SET_ORDER)

	SET @NEW_REVIEW_SET_ID = @@IDENTITY


SET NOCOUNT OFF
GO
USE [Reviewer]
GO
/****** Object:  StoredProcedure [dbo].[st_ReviewSetUpdate]    Script Date: 03/04/2026 12:29:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   procedure [dbo].[st_ReviewSetUpdate]
(
	@REVIEW_SET_ID INT,
	@SET_ID INT,
	@ALLOW_CODING_EDITS BIT,
	@CODING_IS_FINAL BIT,
	@SET_NAME NVARCHAR(255),
	@SET_ORDER INT,
	@SET_DESCRIPTION nvarchar(max),
	@ITEM_SET_ID BIGINT = NULL,
	@IS_COMPLETED BIT = NULL,
	@IS_LOCKED BIT = NULL,
	@REVIEW_ID INT,
	@USER_CAN_EDIT_URLS BIT = 'False'
)

As

SET NOCOUNT ON


declare @check int = 0
set @check = (select count(REVIEW_SET_ID) from 
TB_REVIEW_SET where REVIEW_SET_ID = @REVIEW_SET_ID and REVIEW_ID = @REVIEW_ID)
if(@check != 1) return

UPDATE TB_SET SET SET_NAME = @SET_NAME, SET_DESCRIPTION = @SET_DESCRIPTION, USER_CAN_EDIT_URLS = @USER_CAN_EDIT_URLS
	WHERE SET_ID = @SET_ID
UPDATE TB_REVIEW_SET SET ALLOW_CODING_EDITS = @ALLOW_CODING_EDITS,
	CODING_IS_FINAL = @CODING_IS_FINAL,
	SET_ORDER = @SET_ORDER
WHERE REVIEW_SET_ID = @REVIEW_SET_ID
	
IF (@ITEM_SET_ID > 0)
BEGIN
	UPDATE TB_ITEM_SET
	SET IS_COMPLETED = @IS_COMPLETED, IS_LOCKED = @IS_LOCKED
	WHERE ITEM_SET_ID = @ITEM_SET_ID
END

SET NOCOUNT OFF
GO