USE [Reviewer]
GO


GO

/****** Object:  Table [dbo].[TB_META_ANALYSIS_FILTER_SETTING]    Script Date: 14/04/2023 11:02:41 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_META_ANALYSIS_FILTER_SETTING]') AND type in (N'U'))
BEGIN
	ALTER TABLE [dbo].[TB_META_ANALYSIS_FILTER_SETTING] DROP CONSTRAINT [FK_TB_META_ANALYSIS_FILTER_SETTING_TB_META_ANALYSIS]
	DROP TABLE [dbo].[TB_META_ANALYSIS_FILTER_SETTING]
END
GO

/****** Object:  Table [dbo].[TB_META_ANALYSIS_FILTER_SETTING]    Script Date: 14/04/2023 11:02:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_META_ANALYSIS_FILTER_SETTING](
	[META_ANALYSIS_FILTER_SETTING_ID] [int] IDENTITY(1,1) NOT NULL,
	[META_ANALYSIS_ID] [int] NOT NULL,
	[COLUMN_NAME] [varchar](20) NOT NULL,
	[SELECTED_VALUES] [nvarchar](500) NULL,
	[FILTER_1_VALUE] [nvarchar](500) NULL,
	[FILTER_1_OPERATOR] [varchar](30) NULL,
	[FILTER_1_CASE_SENSITIVE] [bit] NULL,
	[FIELD_FILTER_LOGICAL_OPERATOR] [varchar](3) NULL,
	[FILTER_2_VALUE] [nvarchar](500) NULL,
	[FILTER_2_OPERATOR] [varchar](30) NULL,
	[FILTER_2_CASE_SENSITIVE] [bit] NULL,
 CONSTRAINT [PK_TB_META_ANALYSIS_FILTER_SETTING] PRIMARY KEY CLUSTERED 
(
	[META_ANALYSIS_FILTER_SETTING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_META_ANALYSIS_FILTER_SETTING]  WITH CHECK ADD  CONSTRAINT [FK_TB_META_ANALYSIS_FILTER_SETTING_TB_META_ANALYSIS] FOREIGN KEY([META_ANALYSIS_ID])
REFERENCES [dbo].[TB_META_ANALYSIS] ([META_ANALYSIS_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_META_ANALYSIS_FILTER_SETTING] CHECK CONSTRAINT [FK_TB_META_ANALYSIS_FILTER_SETTING_TB_META_ANALYSIS]
GO

/****** Object:  StoredProcedure [dbo].[st_MetaAnalysisFilterSettings]    Script Date: 17/04/2023 13:37:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_MetaAnalysisFilterSettings]
(
	@REVIEW_ID INT,
	@META_ANALYSIS_ID INT
)

As

SET NOCOUNT ON

	SELECT FS.* from 
	TB_META_ANALYSIS ma
	inner join TB_META_ANALYSIS_FILTER_SETTING FS on FS.META_ANALYSIS_ID = MA.META_ANALYSIS_ID and MA.META_ANALYSIS_ID = @META_ANALYSIS_ID and MA.REVIEW_ID = @REVIEW_ID

SET NOCOUNT OFF
GO

/****** Object:  StoredProcedure [dbo].[st_MetaAnalysisFilterSettingCreate]    Script Date: 17/04/2023 13:37:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_MetaAnalysisFilterSettingCreate]
(
	@REVIEW_ID INT
	,@META_ANALYSIS_ID INT
	,@COLUMN_NAME varchar(20)
	,@SELECTED_VALUES nvarchar(500)
	,@FILTER_1_VALUE nvarchar(500)
	,@FILTER_1_OPERATOR varchar(30)
	,@FILTER_1_CASE_SENSITIVE bit = 0
	,@FIELD_FILTER_LOGICAL_OPERATOR varchar(3)
	,@FILTER_2_VALUE nvarchar(500)
	,@FILTER_2_OPERATOR varchar(30)
	,@FILTER_2_CASE_SENSITIVE bit = 0

	,@META_ANALYSIS_FILTER_SETTING_ID INT = null OUTPUT 
)

As

SET NOCOUNT ON

	declare @check int = (select count(*) from TB_META_ANALYSIS where REVIEW_ID = @REVIEW_ID and META_ANALYSIS_ID = @META_ANALYSIS_ID)
	if @check is null and @check != 1
	BEGIN
		set @META_ANALYSIS_FILTER_SETTING_ID = -1
		return
	END
	INSERT INTO TB_META_ANALYSIS_FILTER_SETTING
           (META_ANALYSIS_ID
           ,COLUMN_NAME
           ,SELECTED_VALUES
           ,FILTER_1_VALUE
           ,FILTER_1_OPERATOR
           ,FILTER_1_CASE_SENSITIVE
           ,FIELD_FILTER_LOGICAL_OPERATOR
           ,FILTER_2_VALUE
           ,FILTER_2_OPERATOR
           ,FILTER_2_CASE_SENSITIVE)
     VALUES
           (@META_ANALYSIS_ID
			,@COLUMN_NAME
			,@SELECTED_VALUES
			,@FILTER_1_VALUE
			,@FILTER_1_OPERATOR
			,@FILTER_1_CASE_SENSITIVE
			,@FIELD_FILTER_LOGICAL_OPERATOR
			,@FILTER_2_VALUE
			,@FILTER_2_OPERATOR 
			,@FILTER_2_CASE_SENSITIVE)
	set @META_ANALYSIS_FILTER_SETTING_ID = CAST(SCOPE_IDENTITY() AS INT)
SET NOCOUNT OFF
GO

/****** Object:  StoredProcedure [dbo].[st_MetaAnalysisFilterSettingCreate]    Script Date: 17/04/2023 13:37:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_MetaAnalysisFilterSettingUpdate]
(
	@REVIEW_ID INT
	,@META_ANALYSIS_FILTER_SETTING_ID INT 
	,@META_ANALYSIS_ID INT
	,@COLUMN_NAME varchar(20)
	,@SELECTED_VALUES nvarchar(500)
	,@FILTER_1_VALUE nvarchar(500)
	,@FILTER_1_OPERATOR varchar(30)
	,@FILTER_1_CASE_SENSITIVE bit = 0
	,@FIELD_FILTER_LOGICAL_OPERATOR varchar(3)
	,@FILTER_2_VALUE nvarchar(500)
	,@FILTER_2_OPERATOR varchar(30)
	,@FILTER_2_CASE_SENSITIVE bit = 0
)

As

SET NOCOUNT ON

	declare @check int = (select count(*) from TB_META_ANALYSIS where REVIEW_ID = @REVIEW_ID and META_ANALYSIS_ID = @META_ANALYSIS_ID)
	if @check is null and @check != 1 return

	UPDATE TB_META_ANALYSIS_FILTER_SETTING
	SET
           COLUMN_NAME = @COLUMN_NAME
           ,SELECTED_VALUES = @SELECTED_VALUES
           ,FILTER_1_VALUE = @FILTER_1_VALUE
           ,FILTER_1_OPERATOR = @FILTER_1_OPERATOR
           ,FILTER_1_CASE_SENSITIVE = @FILTER_1_CASE_SENSITIVE
           ,FIELD_FILTER_LOGICAL_OPERATOR = @FIELD_FILTER_LOGICAL_OPERATOR
           ,FILTER_2_VALUE = @FILTER_2_VALUE
           ,FILTER_2_OPERATOR = @FILTER_2_OPERATOR 
           ,FILTER_2_CASE_SENSITIVE = @FILTER_2_CASE_SENSITIVE
     where META_ANALYSIS_FILTER_SETTING_ID = @META_ANALYSIS_FILTER_SETTING_ID  and META_ANALYSIS_ID = @META_ANALYSIS_ID
			
SET NOCOUNT OFF
GO

/****** Object:  StoredProcedure [dbo].[st_MetaAnalysisFilterSettingDelete]    Script Date: 17/04/2023 13:37:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER procedure [dbo].[st_MetaAnalysisFilterSettingDelete]
(
	@REVIEW_ID INT
	,@META_ANALYSIS_FILTER_SETTING_ID INT 
	,@META_ANALYSIS_ID INT	
)

As

SET NOCOUNT ON

	declare @check int = (
			select count(*) from TB_META_ANALYSIS MA
				Inner Join TB_META_ANALYSIS_FILTER_SETTING FS on MA.META_ANALYSIS_ID = @META_ANALYSIS_ID and MA.META_ANALYSIS_ID = FS.META_ANALYSIS_ID
						AND MA.REVIEW_ID = @REVIEW_ID
						AND FS.META_ANALYSIS_FILTER_SETTING_ID = @META_ANALYSIS_FILTER_SETTING_ID
			)
	if @check is null and @check != 1 return

	delete from TB_META_ANALYSIS_FILTER_SETTING
     where META_ANALYSIS_FILTER_SETTING_ID = @META_ANALYSIS_FILTER_SETTING_ID  and META_ANALYSIS_ID = @META_ANALYSIS_ID
			
SET NOCOUNT OFF
GO


