USE Reviewer
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
           WHERE TABLE_NAME = N'TB_ITEM_TO_DOCUMENT')
BEGIN
	CREATE TABLE TB_ITEM_TO_DOCUMENT (
	ITEM_ID bigint
	, ITEM_DOCUMENT_ID bigint
	,CONSTRAINT [PK_TB_ITEM_TO_DOCUMENT] PRIMARY KEY (ITEM_ID, ITEM_DOCUMENT_ID)
	,CONSTRAINT FK_TB_ITEM_TO_DOCUMENT_TB_ITEM
		FOREIGN KEY (ITEM_ID)
		REFERENCES TB_ITEM (ITEM_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	,CONSTRAINT FK_TB_ITEM_TO_DOCUMENT_TB_ITEM_DOCUMENT
		FOREIGN KEY (ITEM_DOCUMENT_ID)
		REFERENCES TB_ITEM_DOCUMENT (ITEM_DOCUMENT_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	);
	--one index, reversing the order of the PK which is said to help queries
	EXECUTE sp_executesql N'CREATE NONCLUSTERED INDEX 
		IX_TB_ITEM_TO_DOCUMENT_ITEM_DOCUMENT_ID_ITEM_ID 
		ON TB_ITEM_TO_DOCUMENT (ITEM_DOCUMENT_ID, ITEM_ID);'
	EXECUTE sp_executesql N'INSERT INTO TB_ITEM_TO_DOCUMENT SELECT ITEM_ID, ITEM_DOCUMENT_ID from TB_ITEM_DOCUMENT;'
	EXEC sp_rename 'dbo.TB_ITEM_DOCUMENT.ITEM_ID', 'ITEM_ID_STALE', 'COLUMN';
	---TODO!!!! remove FK to TB_ITEM!!!
	
END
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_tb_ITEM_DOCUMENT_tb_ITEM')
BEGIN
	print 'dropping FK_tb_ITEM_DOCUMENT_tb_ITEM'
    EXECUTE sp_executesql N'ALTER TABLE dbo.TB_ITEM_DOCUMENT DROP CONSTRAINT FK_tb_ITEM_DOCUMENT_tb_ITEM'
END

Use ReviewerAdmin
GO

IF NOT EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_TO_DOCUMENT')
BEGIN
 print 'creating SYNONYM sTB_ITEM_TO_DOCUMENT'
 EXECUTE sp_executesql N'Use ReviewerAdmin; CREATE SYNONYM sTB_ITEM_TO_DOCUMENT FOR Reviewer.dbo.TB_ITEM_TO_DOCUMENT;'
END
GO
