Use Reviewer
GO

IF COL_LENGTH('dbo.TB_SOURCE', 'NOTES') <= 8000
BEGIN 
	--select 'I will do it'
	print 'Expanding TB_SOURCE.NOTES column'
	ALTER TABLE TB_SOURCE DROP CONSTRAINT [DF_TB_SOURCE_NOTES]
	ALTER TABLE TB_SOURCE ALTER COLUMN NOTES NVARCHAR (MAX) NOT NULL;
	ALTER TABLE TB_SOURCE ADD CONSTRAINT [DF_TB_SOURCE_NOTES]  DEFAULT ('') FOR [NOTES]
END
GO