--go to new structure supporting doc dedup - part 1 data structures

USE Reviewer
GO


if (select count(distinct z.Zotero_Item_Document_ID)
	from TB_ZOTERO_ITEM_DOCUMENT z
	inner join TB_ITEM_DOCUMENT itd on z.ItemDocumentId = itd.ITEM_DOCUMENT_ID
	inner join TB_ITEM_REVIEW ir on itd.ITEM_ID = ir.ITEM_ID) != (select count(*) from TB_ZOTERO_ITEM_DOCUMENT)
BEGIN 
	SELECT * from TB_ZOTERO_ITEM_DOCUMENT z
	inner join TB_ITEM_DOCUMENT itd on z.ItemDocumentId = itd.ITEM_DOCUMENT_ID
	inner join TB_ITEM_REVIEW ir on itd.ITEM_ID = ir.ITEM_ID
	if (1 = 1) THROW 51000, 'Will delete data from TB_ZOTERO_ITEM_DOCUMENT!!!!', 1;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
           WHERE TABLE_NAME = N'TB_ITEM_TO_DOCUMENT')
BEGIN
	CREATE TABLE TB_ITEM_TO_DOCUMENT (
	ITEM_ID bigint
	, ITEM_DOCUMENT_ID bigint
	, DOCUMENT_TITLE nvarchar(255)
	,CONSTRAINT [PK_TB_ITEM_TO_DOCUMENT] PRIMARY KEY (ITEM_ID, ITEM_DOCUMENT_ID)
	,CONSTRAINT FK_TB_ITEM_TO_DOCUMENT_TB_ITEM
		FOREIGN KEY (ITEM_ID)
		REFERENCES TB_ITEM (ITEM_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	,CONSTRAINT FK_TB_ITEM_TO_DOCUMENT_TB_ITEM_DOCUMENT
		FOREIGN KEY (ITEM_DOCUMENT_ID)
		REFERENCES TB_ITEM_DOCUMENT (ITEM_DOCUMENT_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	);
	--one index, reversing the order of the PK which is said to help queries
	EXECUTE sp_executesql N'CREATE NONCLUSTERED INDEX 
		IX_TB_ITEM_TO_DOCUMENT_ITEM_DOCUMENT_ID_ITEM_ID 
		ON TB_ITEM_TO_DOCUMENT (ITEM_DOCUMENT_ID, ITEM_ID);'
	EXECUTE sp_executesql N'INSERT INTO TB_ITEM_TO_DOCUMENT SELECT ITEM_ID, ITEM_DOCUMENT_ID, DOCUMENT_TITLE from TB_ITEM_DOCUMENT;'
	EXEC sp_rename 'dbo.TB_ITEM_DOCUMENT.ITEM_ID', 'ITEM_ID_STALE', 'COLUMN';
	EXEC sp_rename 'dbo.TB_ITEM_DOCUMENT.DOCUMENT_TITLE', 'DOCUMENT_TITLE_STALE', 'COLUMN';
	---TODO!!!! remove FK to TB_ITEM!!!
	
END
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_tb_ITEM_DOCUMENT_tb_ITEM')
BEGIN
	print 'dropping FK_tb_ITEM_DOCUMENT_tb_ITEM'
    EXECUTE sp_executesql N'ALTER TABLE dbo.TB_ITEM_DOCUMENT DROP CONSTRAINT FK_tb_ITEM_DOCUMENT_tb_ITEM'
END

Use ReviewerAdmin
GO

IF NOT EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_TO_DOCUMENT')
BEGIN
 print 'creating SYNONYM sTB_ITEM_TO_DOCUMENT'
 EXECUTE sp_executesql N'Use ReviewerAdmin; CREATE SYNONYM sTB_ITEM_TO_DOCUMENT FOR Reviewer.dbo.TB_ITEM_TO_DOCUMENT;'
END
GO

USE Reviewer
GO

IF COL_LENGTH('dbo.TB_ZOTERO_ITEM_DOCUMENT', 'ITEM_REVIEW_ID') IS NULL
BEGIN
	ALTER TABLE dbo.TB_ZOTERO_ITEM_DOCUMENT ADD
		ITEM_REVIEW_ID bigint NULL
	EXECUTE sp_executesql N'update TB_ZOTERO_ITEM_DOCUMENT set ITEM_REVIEW_ID = ir.ITEM_REVIEW_ID
	from TB_ZOTERO_ITEM_DOCUMENT z
	inner join TB_ITEM_TO_DOCUMENT itd on z.ItemDocumentId = itd.ITEM_DOCUMENT_ID
	inner join TB_ITEM_REVIEW ir on itd.ITEM_ID = ir.ITEM_ID'

	EXECUTE sp_executesql N'delete from TB_ZOTERO_ITEM_DOCUMENT where ITEM_REVIEW_ID is null'
	EXECUTE sp_executesql N'ALTER TABLE [dbo].[TB_ZOTERO_ITEM_DOCUMENT]  WITH CHECK ADD  CONSTRAINT [FK_tb_ZOTERO_ITEM_DOCUMENTtb_ITEM_REVIEW] FOREIGN KEY([ITEM_REVIEW_ID])
		REFERENCES [dbo].[TB_ITEM_REVIEW] ([ITEM_REVIEW_ID])
		ON UPDATE CASCADE
		ON DELETE CASCADE'
	EXECUTE sp_executesql N'ALTER TABLE [dbo].[TB_ITEM_REVIEW] CHECK CONSTRAINT [FK_tb_ZOTERO_ITEM_DOCUMENTtb_ITEM_REVIEW]'
END
GO



GO


GO


