USE [tempTestReviewerAdmin]
GO
IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SITE_LIC')
 DROP SYNONYM sTB_SITE_LIC;

CREATE SYNONYM sTB_SITE_LIC FOR tempTestReviewer.dbo.TB_SITE_LIC;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_CONTACT')
 DROP SYNONYM sTB_CONTACT;

CREATE SYNONYM sTB_CONTACT FOR tempTestReviewer.dbo.TB_CONTACT;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_REVIEW')
 DROP SYNONYM sTB_REVIEW;

CREATE SYNONYM sTB_REVIEW FOR tempTestReviewer.dbo.TB_REVIEW;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ATTRIBUTE_SET')
 DROP SYNONYM sTB_ATTRIBUTE_SET;

CREATE SYNONYM sTB_ATTRIBUTE_SET FOR tempTestReviewer.dbo.TB_ATTRIBUTE_SET;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ATTRIBUTE')
 DROP SYNONYM sTB_ATTRIBUTE;

CREATE SYNONYM sTB_ATTRIBUTE FOR tempTestReviewer.dbo.TB_ATTRIBUTE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SITE_LIC_CONTACT')
 DROP SYNONYM sTB_SITE_LIC_CONTACT;

CREATE SYNONYM sTB_SITE_LIC_CONTACT FOR tempTestReviewer.dbo.TB_SITE_LIC_CONTACT;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SITE_LIC_REVIEW')
 DROP SYNONYM sTB_SITE_LIC_REVIEW;

CREATE SYNONYM sTB_SITE_LIC_REVIEW FOR tempTestReviewer.dbo.TB_SITE_LIC_REVIEW;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_REVIEW_CONTACT')
 DROP SYNONYM sTB_REVIEW_CONTACT;

CREATE SYNONYM sTB_REVIEW_CONTACT FOR tempTestReviewer.dbo.TB_REVIEW_CONTACT;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_CONTACT_REVIEW_ROLE')
 DROP SYNONYM sTB_CONTACT_REVIEW_ROLE;

CREATE SYNONYM sTB_CONTACT_REVIEW_ROLE FOR tempTestReviewer.dbo.TB_CONTACT_REVIEW_ROLE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SET')
 DROP SYNONYM sTB_SET;

CREATE SYNONYM sTB_SET FOR tempTestReviewer.dbo.TB_SET;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_REVIEW_SET')
 DROP SYNONYM sTB_REVIEW_SET;

CREATE SYNONYM sTB_REVIEW_SET FOR tempTestReviewer.dbo.TB_REVIEW_SET;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SET_TYPE')
 DROP SYNONYM sTB_SET_TYPE;

CREATE SYNONYM sTB_SET_TYPE FOR tempTestReviewer.dbo.TB_SET_TYPE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM')
 DROP SYNONYM sTB_ITEM;

CREATE SYNONYM sTB_ITEM FOR tempTestReviewer.dbo.TB_ITEM;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_REVIEW')
 DROP SYNONYM sTB_ITEM_REVIEW;

CREATE SYNONYM sTB_ITEM_REVIEW FOR tempTestReviewer.dbo.TB_ITEM_REVIEW;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_AUTHOR')
 DROP SYNONYM sTB_ITEM_AUTHOR;

CREATE SYNONYM sTB_ITEM_AUTHOR FOR tempTestReviewer.dbo.TB_ITEM_AUTHOR;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SOURCE')
 DROP SYNONYM sTB_SOURCE;

CREATE SYNONYM sTB_SOURCE FOR tempTestReviewer.dbo.TB_SOURCE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_SOURCE')
 DROP SYNONYM sTB_ITEM_SOURCE;

CREATE SYNONYM sTB_ITEM_SOURCE FOR tempTestReviewer.dbo.TB_ITEM_SOURCE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_DUPLICATE_GROUP')
 DROP SYNONYM sTB_ITEM_DUPLICATE_GROUP;

CREATE SYNONYM sTB_ITEM_DUPLICATE_GROUP FOR tempTestReviewer.dbo.TB_ITEM_DUPLICATE_GROUP;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_DUPLICATE_GROUP_MEMBERS')
 DROP SYNONYM sTB_ITEM_DUPLICATE_GROUP_MEMBERS;

CREATE SYNONYM sTB_ITEM_DUPLICATE_GROUP_MEMBERS FOR tempTestReviewer.dbo.TB_ITEM_DUPLICATE_GROUP_MEMBERS;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_SET')
 DROP SYNONYM sTB_ITEM_SET;

CREATE SYNONYM sTB_ITEM_SET FOR tempTestReviewer.dbo.TB_ITEM_SET;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_ATTRIBUTE')
 DROP SYNONYM sTB_ITEM_ATTRIBUTE;

CREATE SYNONYM sTB_ITEM_ATTRIBUTE FOR tempTestReviewer.dbo.TB_ITEM_ATTRIBUTE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_OUTCOME')
 DROP SYNONYM sTB_ITEM_OUTCOME;

CREATE SYNONYM sTB_ITEM_OUTCOME FOR tempTestReviewer.dbo.TB_ITEM_OUTCOME;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_OUTCOME_ATTRIBUTE')
 DROP SYNONYM sTB_ITEM_OUTCOME_ATTRIBUTE;

CREATE SYNONYM sTB_ITEM_OUTCOME_ATTRIBUTE FOR tempTestReviewer.dbo.TB_ITEM_OUTCOME_ATTRIBUTE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_WORK_ALLOCATION')
 DROP SYNONYM sTB_WORK_ALLOCATION;

CREATE SYNONYM sTB_WORK_ALLOCATION FOR tempTestReviewer.dbo.TB_WORK_ALLOCATION;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_DIAGRAM')
 DROP SYNONYM sTB_DIAGRAM;

CREATE SYNONYM sTB_DIAGRAM FOR tempTestReviewer.dbo.TB_DIAGRAM;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SEARCH')
 DROP SYNONYM sTB_SEARCH;

CREATE SYNONYM sTB_SEARCH FOR tempTestReviewer.dbo.TB_SEARCH;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_SEARCH_ITEM')
 DROP SYNONYM sTB_SEARCH_ITEM;

CREATE SYNONYM sTB_SEARCH_ITEM FOR tempTestReviewer.dbo.TB_SEARCH_ITEM;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_DOCUMENT')
 DROP SYNONYM sTB_ITEM_DOCUMENT;

CREATE SYNONYM sTB_ITEM_DOCUMENT FOR tempTestReviewer.dbo.TB_ITEM_DOCUMENT;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_REPORT')
 DROP SYNONYM sTB_REPORT;

CREATE SYNONYM sTB_REPORT FOR tempTestReviewer.dbo.TB_REPORT;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_REPORT_COLUMN')
 DROP SYNONYM sTB_REPORT_COLUMN;

CREATE SYNONYM sTB_REPORT_COLUMN FOR tempTestReviewer.dbo.TB_REPORT_COLUMN;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_REPORT_COLUMN_CODE')
 DROP SYNONYM sTB_REPORT_COLUMN_CODE;

CREATE SYNONYM sTB_REPORT_COLUMN_CODE FOR tempTestReviewer.dbo.TB_REPORT_COLUMN_CODE;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_META_ANALYSIS')
 DROP SYNONYM sTB_META_ANALYSIS;

CREATE SYNONYM sTB_META_ANALYSIS FOR tempTestReviewer.dbo.TB_META_ANALYSIS;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_META_ANALYSIS_OUTCOME')
 DROP SYNONYM sTB_META_ANALYSIS_OUTCOME;

CREATE SYNONYM sTB_META_ANALYSIS_OUTCOME FOR tempTestReviewer.dbo.TB_META_ANALYSIS_OUTCOME;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_ITEM_LINK')
 DROP SYNONYM sTB_ITEM_LINK;

CREATE SYNONYM sTB_ITEM_LINK FOR tempTestReviewer.dbo.TB_ITEM_LINK;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_WEBDB')
 DROP SYNONYM sTB_WEBDB;

CREATE SYNONYM sTB_WEBDB FOR tempTestReviewer.dbo.TB_WEBDB;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sfn_IsAttributeInTree')
 DROP SYNONYM sfn_IsAttributeInTree;

CREATE SYNONYM sfn_IsAttributeInTree FOR Reviewer.dbo.fn_IsAttributeInTree;


 GO
 USE [tempTestReviewer]
 GO
 
IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_LOGON_TICKET')
 DROP SYNONYM sTB_LOGON_TICKET;

CREATE SYNONYM sTB_LOGON_TICKET FOR tempTestReviewerAdmin.dbo.TB_LOGON_TICKET;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_MANAGEMENT_SETTINGS')
 DROP SYNONYM sTB_MANAGEMENT_SETTINGS;

CREATE SYNONYM sTB_MANAGEMENT_SETTINGS FOR tempTestReviewerAdmin.dbo.TB_MANAGEMENT_SETTINGS;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_TEMPLATE_REVIEW')
 DROP SYNONYM sTB_TEMPLATE_REVIEW;

CREATE SYNONYM sTB_TEMPLATE_REVIEW FOR tempTestReviewerAdmin.dbo.TB_TEMPLATE_REVIEW;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sTB_TEMPLATE_REVIEW_SET')
 DROP SYNONYM sTB_TEMPLATE_REVIEW_SET;

CREATE SYNONYM sTB_TEMPLATE_REVIEW_SET FOR tempTestReviewerAdmin.dbo.TB_TEMPLATE_REVIEW_SET;


IF EXISTS(SELECT * FROM sys.synonyms where name = 'sst_LogonTicket_Insert')
 DROP SYNONYM sst_LogonTicket_Insert;

CREATE SYNONYM sst_LogonTicket_Insert FOR tempTestReviewerAdmin.dbo.st_LogonTicket_Insert;

